-- Generated by scripts/render-seed-migration.ts from the reviewed seed bundle.
-- Additive expansion for: orient-ra-ac0m03s.

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://orient-watch.com/en/orient/collection/classic/classic-and-simple-style-38/RA-AC0M03S/', 'https://orient-watch.com/en/orient/collection/classic/classic-and-simple-style-38/RA-AC0M03S/', 'Classic & Simple Style 38 — RA-AC0M03S', 'Orient', 'manufacturer_product', '2026-08-29T07:18:12Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.orientwatch.co.uk/or/en_GB/brands/orient/orient-bambino-38mm/p/RA-AC0M03S', 'https://www.orientwatch.co.uk/or/en_GB/brands/orient/orient-bambino-38mm/p/RA-AC0M03S', 'Orient Bambino 38mm — RA-AC0M03S', 'Orient UK', 'manufacturer_product', '2026-08-29T07:18:12Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.orientwatchusa.com/products/ra-ac0m03s30b', 'https://www.orientwatchusa.com/products/ra-ac0m03s30b', 'Orient Bambino Version 7 — RA-AC0M03S30B', 'Orient Watch USA', 'manufacturer_product', '2026-08-29T07:18:12Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.orientwatchusa.com/blogs/orient-blog/how-to-remove-a-spring-bar', 'https://www.orientwatchusa.com/blogs/orient-blog/how-to-remove-a-spring-bar', 'How to Remove a Spring Bar', 'Orient Watch USA', 'manufacturer_manual', '2026-08-29T07:53:23Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://delugs.com/blogs/best-straps/best-straps-for-orient-bambino-38mm', 'https://delugs.com/blogs/best-straps/best-straps-for-orient-bambino-38mm', 'Best Straps for the Orient Bambino 38mm — RA-AC0M03S', 'Delugs', 'secondary_editorial', '2026-08-29T07:53:23Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.brands (slug, name, review_status)
values ('orient', 'Orient', 'accepted')
on conflict (slug) do update set name = excluded.name, review_status = 'accepted', updated_at = now();

insert into public.collections (brand_id, slug, name, review_status)
select id, 'classic-simple-style-38', 'Classic & Simple Style 38', 'accepted'
from public.brands where slug = 'orient'
on conflict (brand_id, slug) do update set name = excluded.name, review_status = 'accepted', updated_at = now();

insert into public.reference_models (collection_id, slug, model_name, review_status)
select c.id, 'bambino-38mm', 'Bambino 38mm', 'accepted'
from public.collections c join public.brands b on b.id = c.brand_id
where b.slug = 'orient' and c.slug = 'classic-simple-style-38'
on conflict (collection_id, slug) do update set model_name = excluded.model_name, review_status = 'accepted', updated_at = now();

insert into public.reference_variants (
  reference_model_id, variant_key, reference_code, variant_name,
  case_material, caseback_material, bracelet_material, strap_material,
  nickel_contact_risk, case_diameter_mm, case_thickness_mm, lug_to_lug_mm,
  lug_to_lug_measured, lug_width_mm, lug_curvature, integrated_bracelet,
  weight_full_g, movement_type, caliber_ref, power_reserve_h,
  accuracy_lower_seconds, accuracy_upper_seconds, accuracy_period_days,
  water_resistance_m, crown_type, crown_position, crystal, lume_grade,
  bracelet_attachment, shock_resistant, production_status, review_status
)
values (
  (select rm.id from public.reference_models rm join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and c.slug = 'classic-simple-style-38' and rm.slug = 'bambino-38mm'), 'orient-ra-ac0m03s', 'RA-AC0M03S', 'White dial · black leather strap',
  'stainless steel', 'stainless steel with flat crystal display back', null, 'black leather',
  null, 38.4, 12.5, 44,
  false, 20, null, false,
  54, 'automatic', 'F6724', 40,
  -15, 25, 1,
  30, 'push_pull', null, 'mineral', 'none',
  'spring_bar', null, 'current', 'accepted'
)
on conflict (reference_model_id, variant_key) do update set
  reference_code = excluded.reference_code,
  variant_name = excluded.variant_name,
  case_material = excluded.case_material,
  caseback_material = excluded.caseback_material,
  bracelet_material = excluded.bracelet_material,
  strap_material = excluded.strap_material,
  nickel_contact_risk = excluded.nickel_contact_risk,
  case_diameter_mm = excluded.case_diameter_mm,
  case_thickness_mm = excluded.case_thickness_mm,
  lug_to_lug_mm = excluded.lug_to_lug_mm,
  lug_to_lug_measured = excluded.lug_to_lug_measured,
  lug_width_mm = excluded.lug_width_mm,
  lug_curvature = excluded.lug_curvature,
  integrated_bracelet = excluded.integrated_bracelet,
  weight_full_g = excluded.weight_full_g,
  movement_type = excluded.movement_type,
  caliber_ref = excluded.caliber_ref,
  power_reserve_h = excluded.power_reserve_h,
  accuracy_lower_seconds = excluded.accuracy_lower_seconds,
  accuracy_upper_seconds = excluded.accuracy_upper_seconds,
  accuracy_period_days = excluded.accuracy_period_days,
  water_resistance_m = excluded.water_resistance_m,
  crown_type = excluded.crown_type,
  crown_position = excluded.crown_position,
  crystal = excluded.crystal,
  lume_grade = excluded.lume_grade,
  bracelet_attachment = excluded.bracelet_attachment,
  shock_resistant = excluded.shock_resistant,
  production_status = excluded.production_status,
  review_status = 'accepted',
  updated_at = now();

update public.reference_variants
set product_url = 'https://orient-watch.com/en/orient/collection/classic/classic-and-simple-style-38/RA-AC0M03S/', updated_at = now()
where id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s')
  and product_url is distinct from 'https://orient-watch.com/en/orient/collection/classic/classic-and-simple-style-38/RA-AC0M03S/';

insert into public.reference_complications (reference_variant_id, complication)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'date')
on conflict (reference_variant_id, complication) do nothing;

insert into public.price_snapshots (
  reference_variant_id, kind, condition, currency, amount_low_minor,
  market_country_code, observed_at, stale_after, review_status
)
select (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'retail', 'new', 'GBP', 29499,
  'GB', '2026-08-29T07:18:12Z'::timestamptz, '2027-02-25T07:18:12Z'::timestamptz, 'accepted'
where not exists (
  select 1 from public.price_snapshots ps
  where ps.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s')
    and ps.kind = 'retail' and ps.condition = 'new'
    and ps.currency = 'GBP'
    and ps.observed_at = '2026-08-29T07:18:12Z'::timestamptz
);

insert into public.market_snapshots (
  reference_variant_id, market_country_code, availability, observed_at,
  stale_after, review_status
)
  select (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'GB', 'unavailable',
  '2026-08-29T07:18:12Z'::timestamptz,
  '2026-09-28T07:18:12Z'::timestamptz, 'accepted'
where not exists (
  select 1 from public.market_snapshots ms
  where ms.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s')
    and ms.market_country_code = 'GB'
    and ms.observed_at = '2026-08-29T07:18:12Z'::timestamptz
);

insert into public.reference_deployment_profiles (
  reference_variant_id, environment, review_status
)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'studio_desk_daily', 'accepted')
on conflict (reference_variant_id, environment) do update set
  review_status = 'accepted';

insert into public.reference_deployment_profiles (
  reference_variant_id, environment, review_status
)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'formal_architectural', 'accepted')
on conflict (reference_variant_id, environment) do update set
  review_status = 'accepted';

insert into public.reference_ownership_friction_profiles (
  reference_variant_id, friction_level, review_status
)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'workhorse_mechanical', 'accepted')
on conflict (reference_variant_id, friction_level) do update set
  review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'primary_archetype', 'accessible_classic_date', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'social_signal', 'quiet_continuity', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'aesthetic_dna', 'mid_century_industrial', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'emotional_objective', 'dependability', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'emotional_objective', 'milestone', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'identity', '2e9f0e0027d6be054955972afd10d2e52acc21a046a28812883aa44c95ff1a07', (select id from public.sources where url = 'https://orient-watch.com/en/orient/collection/classic/classic-and-simple-style-38/RA-AC0M03S/' and retrieved_at = '2026-08-29T07:18:12Z'::timestamptz),
  '2026-08-29T07:18:12Z'::timestamptz, '2026-08-29T07:18:12Z'::timestamptz,
  '2026-08-29T07:18:12Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'materials', '56ae5f12c31a441104fe8dc6d14cd980083a23436ffe71279eaa10af5c7f343b', (select id from public.sources where url = 'https://orient-watch.com/en/orient/collection/classic/classic-and-simple-style-38/RA-AC0M03S/' and retrieved_at = '2026-08-29T07:18:12Z'::timestamptz),
  '2026-08-29T07:18:12Z'::timestamptz, '2026-08-29T07:18:12Z'::timestamptz,
  '2026-08-29T07:18:12Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'productionStatus', '694df57a7909d9f9edbd3acb4ccfce5fbee156fab749383121f17fef16bbab57', (select id from public.sources where url = 'https://orient-watch.com/en/orient/collection/classic/classic-and-simple-style-38/RA-AC0M03S/' and retrieved_at = '2026-08-29T07:18:12Z'::timestamptz),
  '2026-08-29T07:18:12Z'::timestamptz, '2026-08-29T07:18:12Z'::timestamptz,
  '2026-08-29T07:18:12Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'caseDiameterMm', '4cc5aeb822d81710fc92731f129b46a2790fd35eeda44268ff3e2b3897ab23a7', (select id from public.sources where url = 'https://orient-watch.com/en/orient/collection/classic/classic-and-simple-style-38/RA-AC0M03S/' and retrieved_at = '2026-08-29T07:18:12Z'::timestamptz),
  '2026-08-29T07:18:12Z'::timestamptz, '2026-08-29T07:18:12Z'::timestamptz,
  '2026-08-29T07:18:12Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'caseThicknessMm', 'b902cc4550838229a710bfec4c38cbc7eb11082367a409df9135e7f007a96bda', (select id from public.sources where url = 'https://orient-watch.com/en/orient/collection/classic/classic-and-simple-style-38/RA-AC0M03S/' and retrieved_at = '2026-08-29T07:18:12Z'::timestamptz),
  '2026-08-29T07:18:12Z'::timestamptz, '2026-08-29T07:18:12Z'::timestamptz,
  '2026-08-29T07:18:12Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'lugToLugMm', '71ee45a3c0db9a9865f7313dd3372cf60dca6479d46261f3542eb9346e4a04d6', (select id from public.sources where url = 'https://orient-watch.com/en/orient/collection/classic/classic-and-simple-style-38/RA-AC0M03S/' and retrieved_at = '2026-08-29T07:18:12Z'::timestamptz),
  '2026-08-29T07:18:12Z'::timestamptz, '2026-08-29T07:18:12Z'::timestamptz,
  '2026-08-29T07:18:12Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'lugWidthMm', 'f5ca38f748a1d6eaf726b8a42fb575c3c71f1864a8143301782de13da2d9202b', (select id from public.sources where url = 'https://orient-watch.com/en/orient/collection/classic/classic-and-simple-style-38/RA-AC0M03S/' and retrieved_at = '2026-08-29T07:18:12Z'::timestamptz),
  '2026-08-29T07:18:12Z'::timestamptz, '2026-08-29T07:18:12Z'::timestamptz,
  '2026-08-29T07:18:12Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'weightFullG', '2fca346db656187102ce806ac732e06a62df0dbb2829e511a770556d398e1a6e', (select id from public.sources where url = 'https://orient-watch.com/en/orient/collection/classic/classic-and-simple-style-38/RA-AC0M03S/' and retrieved_at = '2026-08-29T07:18:12Z'::timestamptz),
  '2026-08-29T07:18:12Z'::timestamptz, '2026-08-29T07:18:12Z'::timestamptz,
  '2026-08-29T07:18:12Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'movement', 'b45a9765d3fa4323ec4b922daee593564bd2f5124bb387111f50c24bfab005b1', (select id from public.sources where url = 'https://orient-watch.com/en/orient/collection/classic/classic-and-simple-style-38/RA-AC0M03S/' and retrieved_at = '2026-08-29T07:18:12Z'::timestamptz),
  '2026-08-29T07:18:12Z'::timestamptz, '2026-08-29T07:18:12Z'::timestamptz,
  '2026-08-29T07:18:12Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'accuracy', 'dfbcd19ae81f521d419dbefef877d60dc25d19575cb9066c6f35030f33f6022b', (select id from public.sources where url = 'https://orient-watch.com/en/orient/collection/classic/classic-and-simple-style-38/RA-AC0M03S/' and retrieved_at = '2026-08-29T07:18:12Z'::timestamptz),
  '2026-08-29T07:18:12Z'::timestamptz, '2026-08-29T07:18:12Z'::timestamptz,
  '2026-08-29T07:18:12Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'waterResistanceM', '624b60c58c9d8bfb6ff1886c2fd605d2adeb6ea4da576068201b6c6958ce93f4', (select id from public.sources where url = 'https://orient-watch.com/en/orient/collection/classic/classic-and-simple-style-38/RA-AC0M03S/' and retrieved_at = '2026-08-29T07:18:12Z'::timestamptz),
  '2026-08-29T07:18:12Z'::timestamptz, '2026-08-29T07:18:12Z'::timestamptz,
  '2026-08-29T07:18:12Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'crystal', '22c5534b9bb5b94643119966014b4f540e7ecd085c27a65061b52e313f357cd9', (select id from public.sources where url = 'https://orient-watch.com/en/orient/collection/classic/classic-and-simple-style-38/RA-AC0M03S/' and retrieved_at = '2026-08-29T07:18:12Z'::timestamptz),
  '2026-08-29T07:18:12Z'::timestamptz, '2026-08-29T07:18:12Z'::timestamptz,
  '2026-08-29T07:18:12Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'lumeGrade', '30a0924a3360be687d1df9fcbbfdff62c01bc0fd14036ab9076cf7f451568666', (select id from public.sources where url = 'https://orient-watch.com/en/orient/collection/classic/classic-and-simple-style-38/RA-AC0M03S/' and retrieved_at = '2026-08-29T07:18:12Z'::timestamptz),
  '2026-08-29T07:18:12Z'::timestamptz, '2026-08-29T07:18:12Z'::timestamptz,
  '2026-08-29T07:18:12Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'dateStatus', '94332144d941eb1212c9af7f968e215a7042bf94925c9c10b21de97a2f0cea06', (select id from public.sources where url = 'https://orient-watch.com/en/orient/collection/classic/classic-and-simple-style-38/RA-AC0M03S/' and retrieved_at = '2026-08-29T07:18:12Z'::timestamptz),
  '2026-08-29T07:18:12Z'::timestamptz, '2026-08-29T07:18:12Z'::timestamptz,
  '2026-08-29T07:18:12Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'eligibleEnvironments', 'e1a5e4b0cda93ec3293ecbfe43603ca3727c13b020e5c516aac5cd66719d4e67', (select id from public.sources where url = 'https://orient-watch.com/en/orient/collection/classic/classic-and-simple-style-38/RA-AC0M03S/' and retrieved_at = '2026-08-29T07:18:12Z'::timestamptz),
  '2026-08-29T07:18:12Z'::timestamptz, '2026-08-29T07:18:12Z'::timestamptz,
  '2026-08-29T07:18:12Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'ownershipFrictionLevels', '582066aec46a0e953a89b01aca2612ef776f66237e411fec8fb5f77652aaee62', (select id from public.sources where url = 'https://orient-watch.com/en/orient/collection/classic/classic-and-simple-style-38/RA-AC0M03S/' and retrieved_at = '2026-08-29T07:18:12Z'::timestamptz),
  '2026-08-29T07:18:12Z'::timestamptz, '2026-08-29T07:18:12Z'::timestamptz,
  '2026-08-29T07:18:12Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'traits', 'c2da39f5e856abb15e27d433f3d0ded375055072ea70fe2b93d397c311a28ec4', (select id from public.sources where url = 'https://orient-watch.com/en/orient/collection/classic/classic-and-simple-style-38/RA-AC0M03S/' and retrieved_at = '2026-08-29T07:18:12Z'::timestamptz),
  '2026-08-29T07:18:12Z'::timestamptz, '2026-08-29T07:18:12Z'::timestamptz,
  '2026-08-29T07:18:12Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'crownType', 'dfaa8e93fc07a2a9141ba5ebaa0c5335b0ca449b86ede61d274b5e63be301863', (select id from public.sources where url = 'https://www.orientwatchusa.com/products/ra-ac0m03s30b' and retrieved_at = '2026-08-29T07:18:12Z'::timestamptz),
  '2026-08-29T07:18:12Z'::timestamptz, '2026-08-29T07:18:12Z'::timestamptz,
  '2026-08-29T07:18:12Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'attachmentType', 'dc8f261bad159c55d8fb5a6cdf75774951c242716e8306aaaad0e1a7b999db27', (select id from public.sources where url = 'https://www.orientwatchusa.com/blogs/orient-blog/how-to-remove-a-spring-bar' and retrieved_at = '2026-08-29T07:53:23Z'::timestamptz),
  '2026-08-29T07:18:12Z'::timestamptz, '2026-08-29T07:53:23Z'::timestamptz,
  '2026-08-29T07:53:23Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'attachmentType', 'dc8f261bad159c55d8fb5a6cdf75774951c242716e8306aaaad0e1a7b999db27', (select id from public.sources where url = 'https://delugs.com/blogs/best-straps/best-straps-for-orient-bambino-38mm' and retrieved_at = '2026-08-29T07:53:23Z'::timestamptz),
  '2026-08-29T07:18:12Z'::timestamptz, '2026-08-29T07:53:23Z'::timestamptz,
  '2026-08-29T07:53:23Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, stale_after, tier, reviewer
)
select 'price_snapshot', ps.id, 'amount_low_minor', 'e908bea5801b8dd320c97a0d2d8abc891a9de61501af7d5137ef1051a46abeec', (select id from public.sources where url = 'https://www.orientwatch.co.uk/or/en_GB/brands/orient/orient-bambino-38mm/p/RA-AC0M03S' and retrieved_at = '2026-08-29T07:18:12Z'::timestamptz),
  ps.observed_at, '2026-08-29T07:18:12Z'::timestamptz,
  '2026-08-29T07:18:12Z'::timestamptz,
  ps.stale_after, 'verified', 'catalogue-expansion-v1'
from public.price_snapshots ps
where ps.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s')
  and ps.kind = 'retail' and ps.condition = 'new'
  and ps.currency = 'GBP'
  and ps.observed_at = '2026-08-29T07:18:12Z'::timestamptz
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, stale_after = excluded.stale_after,
  tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, stale_after, tier, reviewer
)
select 'market_snapshot', ms.id, 'availability', 'ec833b19d159ba681e50bda3b3397116bad0053bb383e42149b8ac22a17a580f', (select id from public.sources where url = 'https://www.orientwatch.co.uk/or/en_GB/brands/orient/orient-bambino-38mm/p/RA-AC0M03S' and retrieved_at = '2026-08-29T07:18:12Z'::timestamptz),
  ms.observed_at, '2026-08-29T07:18:12Z'::timestamptz,
  '2026-08-29T07:18:12Z'::timestamptz,
  ms.stale_after, 'verified', 'catalogue-expansion-v1'
from public.market_snapshots ms
where ms.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s')
  and ms.market_country_code = 'GB'
  and ms.observed_at = '2026-08-29T07:18:12Z'::timestamptz
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, stale_after = excluded.stale_after,
  tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.completeness_evaluations (
  subject_type, subject_id, level, filter_contract_version, complete,
  completeness_score, missing_fields, evaluated_at
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'm0', 1,
  true, 1.0000, array[]::text[],
  '2026-08-29T07:18:12Z'::timestamptz
)
on conflict (subject_type, subject_id, level, filter_contract_version) do update set
  complete = excluded.complete,
  completeness_score = excluded.completeness_score,
  missing_fields = excluded.missing_fields,
  evaluated_at = excluded.evaluated_at;

insert into public.completeness_evaluations (
  subject_type, subject_id, level, filter_contract_version, complete,
  completeness_score, missing_fields, evaluated_at
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'm1', 1,
  true, 1.0000, array[]::text[],
  '2026-08-29T07:18:12Z'::timestamptz
)
on conflict (subject_type, subject_id, level, filter_contract_version) do update set
  complete = excluded.complete,
  completeness_score = excluded.completeness_score,
  missing_fields = excluded.missing_fields,
  evaluated_at = excluded.evaluated_at;

insert into public.completeness_evaluations (
  subject_type, subject_id, level, filter_contract_version, complete,
  completeness_score, missing_fields, evaluated_at
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'orient' and rv.variant_key = 'orient-ra-ac0m03s'), 'm2', 1,
  false, 0.6667, array['market']::text[],
  '2026-08-29T07:18:12Z'::timestamptz
)
on conflict (subject_type, subject_id, level, filter_contract_version) do update set
  complete = excluded.complete,
  completeness_score = excluded.completeness_score,
  missing_fields = excluded.missing_fields,
  evaluated_at = excluded.evaluated_at;
