-- Generated by scripts/render-seed-migration.ts from the reviewed seed bundle.
-- Additive expansion for: seiko-hcc004j1.

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.seikowatches.com/us-en/products/presage/hcc004j1', 'https://www.seikowatches.com/us-en/products/presage/hcc004j1', 'Presage Classic Series Seiko 145th Anniversary Limited Edition — HCC004J1', 'Seiko Watch Corporation', 'manufacturer_product', '2026-08-29T08:35:05Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://store.seikowatches.com/products/hcc004j', 'https://store.seikowatches.com/products/hcc004j', 'Presage Classic Series Seiko 145th Anniversary Limited Edition — HCC004J', 'Seiko Watch Corporation', 'manufacturer_product', '2026-08-29T08:35:05Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.seikowatches.com/-/media/HtmlUploader/Common/Seiko/Home/instructions/html/SEIKO_6R51_6R55_6R5H_6R5J_EN/assets/pdf/6R5C_2311_EN.pdf', 'https://www.seikowatches.com/-/media/HtmlUploader/Common/Seiko/Home/instructions/html/SEIKO_6R51_6R55_6R5H_6R5J_EN/assets/pdf/6R5C_2311_EN.pdf', 'Calibres 6R51, 6R55, 6R5H and 6R5J instructions', 'Seiko Watch Corporation', 'manufacturer_manual', '2026-08-29T08:35:05Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://seikoboutique.com.sg/product/seiko-145th-anniversary-limited-edition-presage-classic-automatic-hcc004j1/', 'https://seikoboutique.com.sg/product/seiko-145th-anniversary-limited-edition-presage-classic-automatic-hcc004j1/', 'Seiko 145th Anniversary Limited Edition Presage Classic Automatic — HCC004J1', 'Thong Sia Co. (S) Pte. Ltd. — Seiko official Singapore distributor', 'secondary_editorial', '2026-08-29T08:35:05Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://en.webchronos.net/features/161585/', 'https://en.webchronos.net/features/161585/', 'A deep dive into the Seiko Presage Classic Series 145th Anniversary model', 'Chronos Japan / webChronos', 'secondary_editorial', '2026-08-29T08:35:05Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.louispion.fr/presage-hcc004j1.html', 'https://www.louispion.fr/presage-hcc004j1.html', 'Seiko Presage — HCC004J1', 'Louis Pion', 'secondary_editorial', '2026-08-29T08:35:05Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.brands (slug, name, review_status)
values ('seiko', 'Seiko', 'accepted')
on conflict (slug) do update set name = excluded.name, review_status = 'accepted', updated_at = now();

insert into public.collections (brand_id, slug, name, review_status)
select id, 'presage-classic-series', 'Presage Classic Series', 'accepted'
from public.brands where slug = 'seiko'
on conflict (brand_id, slug) do update set name = excluded.name, review_status = 'accepted', updated_at = now();

insert into public.reference_models (collection_id, slug, model_name, review_status)
select c.id, 'hcc004', 'HCC004', 'accepted'
from public.collections c join public.brands b on b.id = c.brand_id
where b.slug = 'seiko' and c.slug = 'presage-classic-series'
on conflict (collection_id, slug) do update set model_name = excluded.model_name, review_status = 'accepted', updated_at = now();

insert into public.reference_variants (
  reference_model_id, variant_key, reference_code, variant_name,
  case_material, caseback_material, bracelet_material, strap_material,
  nickel_contact_risk, case_diameter_mm, case_thickness_mm, lug_to_lug_mm,
  lug_to_lug_measured, lug_width_mm, lug_curvature, integrated_bracelet,
  weight_full_g, movement_type, caliber_ref, power_reserve_h,
  accuracy_lower_seconds, accuracy_upper_seconds, accuracy_period_days,
  water_resistance_m, crown_type, crown_position, crystal, lume_grade,
  bracelet_attachment, shock_resistant, production_status, review_status
)
values (
  (select rm.id from public.reference_models rm join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and c.slug = 'presage-classic-series' and rm.slug = 'hcc004'), 'seiko-hcc004j1', 'HCC004J1', 'Seiko 145th Anniversary Limited Edition · deep navy cow-leather strap',
  'stainless steel with super-hard coating', 'stainless steel see-through screw caseback', null, 'deep navy cow leather',
  null, 36, 12.5, 41.4,
  false, 18, null, false,
  66, 'automatic', 'Seiko 6R51', 72,
  -15, 25, 1,
  100, 'push_pull', null, 'sapphire', 'none',
  'spring_bar', null, 'current', 'accepted'
)
on conflict (reference_model_id, variant_key) do update set
  reference_code = excluded.reference_code,
  variant_name = excluded.variant_name,
  case_material = excluded.case_material,
  caseback_material = excluded.caseback_material,
  bracelet_material = excluded.bracelet_material,
  strap_material = excluded.strap_material,
  nickel_contact_risk = excluded.nickel_contact_risk,
  case_diameter_mm = excluded.case_diameter_mm,
  case_thickness_mm = excluded.case_thickness_mm,
  lug_to_lug_mm = excluded.lug_to_lug_mm,
  lug_to_lug_measured = excluded.lug_to_lug_measured,
  lug_width_mm = excluded.lug_width_mm,
  lug_curvature = excluded.lug_curvature,
  integrated_bracelet = excluded.integrated_bracelet,
  weight_full_g = excluded.weight_full_g,
  movement_type = excluded.movement_type,
  caliber_ref = excluded.caliber_ref,
  power_reserve_h = excluded.power_reserve_h,
  accuracy_lower_seconds = excluded.accuracy_lower_seconds,
  accuracy_upper_seconds = excluded.accuracy_upper_seconds,
  accuracy_period_days = excluded.accuracy_period_days,
  water_resistance_m = excluded.water_resistance_m,
  crown_type = excluded.crown_type,
  crown_position = excluded.crown_position,
  crystal = excluded.crystal,
  lume_grade = excluded.lume_grade,
  bracelet_attachment = excluded.bracelet_attachment,
  shock_resistant = excluded.shock_resistant,
  production_status = excluded.production_status,
  review_status = 'accepted',
  updated_at = now();

update public.reference_variants
set product_url = 'https://www.seikowatches.com/us-en/products/presage/hcc004j1', updated_at = now()
where id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1')
  and product_url is distinct from 'https://www.seikowatches.com/us-en/products/presage/hcc004j1';



insert into public.price_snapshots (
  reference_variant_id, kind, condition, currency, amount_low_minor,
  market_country_code, observed_at, stale_after, review_status
)
select (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'retail', 'new', 'USD', 100000,
  'US', '2026-08-29T08:35:05Z'::timestamptz, '2027-02-25T08:35:05Z'::timestamptz, 'accepted'
where not exists (
  select 1 from public.price_snapshots ps
  where ps.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1')
    and ps.kind = 'retail' and ps.condition = 'new'
    and ps.currency = 'USD'
    and ps.observed_at = '2026-08-29T08:35:05Z'::timestamptz
);



insert into public.reference_deployment_profiles (
  reference_variant_id, environment, review_status
)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'studio_desk_daily', 'accepted')
on conflict (reference_variant_id, environment) do update set
  review_status = 'accepted';

insert into public.reference_deployment_profiles (
  reference_variant_id, environment, review_status
)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'formal_architectural', 'accepted')
on conflict (reference_variant_id, environment) do update set
  review_status = 'accepted';

insert into public.reference_ownership_friction_profiles (
  reference_variant_id, friction_level, review_status
)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'workhorse_mechanical', 'accepted')
on conflict (reference_variant_id, friction_level) do update set
  review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'primary_archetype', 'compact_classic_no_date', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'social_signal', 'quiet_continuity', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'aesthetic_dna', 'mid_century_industrial', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'emotional_objective', 'milestone', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'identity', '4fcf8c5bc811c01d7c337ad548cda38c3b8912ee5531f65b3a08c3ac8e80ac50', (select id from public.sources where url = 'https://www.seikowatches.com/us-en/products/presage/hcc004j1' and retrieved_at = '2026-08-29T08:35:05Z'::timestamptz),
  '2026-08-29T08:35:05Z'::timestamptz, '2026-08-29T08:35:05Z'::timestamptz,
  '2026-08-29T08:35:05Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'materials', '647ca6163b2e2ca78bc2a7906026627ddde558149b2c2250d5440fdb9ef73e65', (select id from public.sources where url = 'https://www.seikowatches.com/us-en/products/presage/hcc004j1' and retrieved_at = '2026-08-29T08:35:05Z'::timestamptz),
  '2026-08-29T08:35:05Z'::timestamptz, '2026-08-29T08:35:05Z'::timestamptz,
  '2026-08-29T08:35:05Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'productionStatus', '694df57a7909d9f9edbd3acb4ccfce5fbee156fab749383121f17fef16bbab57', (select id from public.sources where url = 'https://www.seikowatches.com/us-en/products/presage/hcc004j1' and retrieved_at = '2026-08-29T08:35:05Z'::timestamptz),
  '2026-08-29T08:35:05Z'::timestamptz, '2026-08-29T08:35:05Z'::timestamptz,
  '2026-08-29T08:35:05Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'caseDiameterMm', '76a50887d8f1c2e9301755428990ad81479ee21c25b43215cf524541e0503269', (select id from public.sources where url = 'https://www.seikowatches.com/us-en/products/presage/hcc004j1' and retrieved_at = '2026-08-29T08:35:05Z'::timestamptz),
  '2026-08-29T08:35:05Z'::timestamptz, '2026-08-29T08:35:05Z'::timestamptz,
  '2026-08-29T08:35:05Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'caseThicknessMm', 'b902cc4550838229a710bfec4c38cbc7eb11082367a409df9135e7f007a96bda', (select id from public.sources where url = 'https://www.seikowatches.com/us-en/products/presage/hcc004j1' and retrieved_at = '2026-08-29T08:35:05Z'::timestamptz),
  '2026-08-29T08:35:05Z'::timestamptz, '2026-08-29T08:35:05Z'::timestamptz,
  '2026-08-29T08:35:05Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'lugToLugMm', '923f3becc67d260b3543d092500f6e5684564879a9286c762236e54b532fa534', (select id from public.sources where url = 'https://www.seikowatches.com/us-en/products/presage/hcc004j1' and retrieved_at = '2026-08-29T08:35:05Z'::timestamptz),
  '2026-08-29T08:35:05Z'::timestamptz, '2026-08-29T08:35:05Z'::timestamptz,
  '2026-08-29T08:35:05Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'lugWidthMm', '4ec9599fc203d176a301536c2e091a19bc852759b255bd6818810a42c5fed14a', (select id from public.sources where url = 'https://www.seikowatches.com/us-en/products/presage/hcc004j1' and retrieved_at = '2026-08-29T08:35:05Z'::timestamptz),
  '2026-08-29T08:35:05Z'::timestamptz, '2026-08-29T08:35:05Z'::timestamptz,
  '2026-08-29T08:35:05Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'movement', '89e82d34d4c9919481483e0ab4b3d32b86402b37118c6a11044341cba802bfe5', (select id from public.sources where url = 'https://www.seikowatches.com/us-en/products/presage/hcc004j1' and retrieved_at = '2026-08-29T08:35:05Z'::timestamptz),
  '2026-08-29T08:35:05Z'::timestamptz, '2026-08-29T08:35:05Z'::timestamptz,
  '2026-08-29T08:35:05Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'accuracy', 'dfbcd19ae81f521d419dbefef877d60dc25d19575cb9066c6f35030f33f6022b', (select id from public.sources where url = 'https://www.seikowatches.com/us-en/products/presage/hcc004j1' and retrieved_at = '2026-08-29T08:35:05Z'::timestamptz),
  '2026-08-29T08:35:05Z'::timestamptz, '2026-08-29T08:35:05Z'::timestamptz,
  '2026-08-29T08:35:05Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'waterResistanceM', 'ad57366865126e55649ecb23ae1d48887544976efea46a48eb5d85a6eeb4d306', (select id from public.sources where url = 'https://www.seikowatches.com/us-en/products/presage/hcc004j1' and retrieved_at = '2026-08-29T08:35:05Z'::timestamptz),
  '2026-08-29T08:35:05Z'::timestamptz, '2026-08-29T08:35:05Z'::timestamptz,
  '2026-08-29T08:35:05Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'crystal', '7191152669ad73162c786dd51b4301ac95d94e7b053dea5f698bd2815785cfef', (select id from public.sources where url = 'https://www.seikowatches.com/us-en/products/presage/hcc004j1' and retrieved_at = '2026-08-29T08:35:05Z'::timestamptz),
  '2026-08-29T08:35:05Z'::timestamptz, '2026-08-29T08:35:05Z'::timestamptz,
  '2026-08-29T08:35:05Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'eligibleEnvironments', 'e1a5e4b0cda93ec3293ecbfe43603ca3727c13b020e5c516aac5cd66719d4e67', (select id from public.sources where url = 'https://www.seikowatches.com/us-en/products/presage/hcc004j1' and retrieved_at = '2026-08-29T08:35:05Z'::timestamptz),
  '2026-08-29T08:35:05Z'::timestamptz, '2026-08-29T08:35:05Z'::timestamptz,
  '2026-08-29T08:35:05Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'ownershipFrictionLevels', '582066aec46a0e953a89b01aca2612ef776f66237e411fec8fb5f77652aaee62', (select id from public.sources where url = 'https://www.seikowatches.com/us-en/products/presage/hcc004j1' and retrieved_at = '2026-08-29T08:35:05Z'::timestamptz),
  '2026-08-29T08:35:05Z'::timestamptz, '2026-08-29T08:35:05Z'::timestamptz,
  '2026-08-29T08:35:05Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'traits', 'a1a7fb4d15a14a8a863abb7cd665cc36919a494229c2368abe6e078f961aca13', (select id from public.sources where url = 'https://www.seikowatches.com/us-en/products/presage/hcc004j1' and retrieved_at = '2026-08-29T08:35:05Z'::timestamptz),
  '2026-08-29T08:35:05Z'::timestamptz, '2026-08-29T08:35:05Z'::timestamptz,
  '2026-08-29T08:35:05Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'weightFullG', '3ada92f28b4ceda38562ebf047c6ff05400d4c572352a1142eedfef67d21e662', (select id from public.sources where url = 'https://store.seikowatches.com/products/hcc004j' and retrieved_at = '2026-08-29T08:35:05Z'::timestamptz),
  '2026-08-29T08:35:05Z'::timestamptz, '2026-08-29T08:35:05Z'::timestamptz,
  '2026-08-29T08:35:05Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'dateStatus', '15dbb2c4361b809a46b847b3b6c071f3c27c096057d31c45351902b79fe39efd', (select id from public.sources where url = 'https://www.seikowatches.com/-/media/HtmlUploader/Common/Seiko/Home/instructions/html/SEIKO_6R51_6R55_6R5H_6R5J_EN/assets/pdf/6R5C_2311_EN.pdf' and retrieved_at = '2026-08-29T08:35:05Z'::timestamptz),
  '2026-08-29T08:35:05Z'::timestamptz, '2026-08-29T08:35:05Z'::timestamptz,
  '2026-08-29T08:35:05Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'crownType', 'dfaa8e93fc07a2a9141ba5ebaa0c5335b0ca449b86ede61d274b5e63be301863', (select id from public.sources where url = 'https://seikoboutique.com.sg/product/seiko-145th-anniversary-limited-edition-presage-classic-automatic-hcc004j1/' and retrieved_at = '2026-08-29T08:35:05Z'::timestamptz),
  '2026-08-29T08:35:05Z'::timestamptz, '2026-08-29T08:35:05Z'::timestamptz,
  '2026-08-29T08:35:05Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'lumeGrade', '30a0924a3360be687d1df9fcbbfdff62c01bc0fd14036ab9076cf7f451568666', (select id from public.sources where url = 'https://seikoboutique.com.sg/product/seiko-145th-anniversary-limited-edition-presage-classic-automatic-hcc004j1/' and retrieved_at = '2026-08-29T08:35:05Z'::timestamptz),
  '2026-08-29T08:35:05Z'::timestamptz, '2026-08-29T08:35:05Z'::timestamptz,
  '2026-08-29T08:35:05Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'dateStatus', '15dbb2c4361b809a46b847b3b6c071f3c27c096057d31c45351902b79fe39efd', (select id from public.sources where url = 'https://seikoboutique.com.sg/product/seiko-145th-anniversary-limited-edition-presage-classic-automatic-hcc004j1/' and retrieved_at = '2026-08-29T08:35:05Z'::timestamptz),
  '2026-08-29T08:35:05Z'::timestamptz, '2026-08-29T08:35:05Z'::timestamptz,
  '2026-08-29T08:35:05Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'lumeGrade', '30a0924a3360be687d1df9fcbbfdff62c01bc0fd14036ab9076cf7f451568666', (select id from public.sources where url = 'https://en.webchronos.net/features/161585/' and retrieved_at = '2026-08-29T08:35:05Z'::timestamptz),
  '2026-08-29T08:35:05Z'::timestamptz, '2026-08-29T08:35:05Z'::timestamptz,
  '2026-08-29T08:35:05Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'eligibleEnvironments', 'e1a5e4b0cda93ec3293ecbfe43603ca3727c13b020e5c516aac5cd66719d4e67', (select id from public.sources where url = 'https://en.webchronos.net/features/161585/' and retrieved_at = '2026-08-29T08:35:05Z'::timestamptz),
  '2026-08-29T08:35:05Z'::timestamptz, '2026-08-29T08:35:05Z'::timestamptz,
  '2026-08-29T08:35:05Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'traits', 'a1a7fb4d15a14a8a863abb7cd665cc36919a494229c2368abe6e078f961aca13', (select id from public.sources where url = 'https://en.webchronos.net/features/161585/' and retrieved_at = '2026-08-29T08:35:05Z'::timestamptz),
  '2026-08-29T08:35:05Z'::timestamptz, '2026-08-29T08:35:05Z'::timestamptz,
  '2026-08-29T08:35:05Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'attachmentType', 'dc8f261bad159c55d8fb5a6cdf75774951c242716e8306aaaad0e1a7b999db27', (select id from public.sources where url = 'https://www.louispion.fr/presage-hcc004j1.html' and retrieved_at = '2026-08-29T08:35:05Z'::timestamptz),
  '2026-08-29T08:35:05Z'::timestamptz, '2026-08-29T08:35:05Z'::timestamptz,
  '2026-08-29T08:35:05Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, stale_after, tier, reviewer
)
select 'price_snapshot', ps.id, 'amount_low_minor', '3bb78535cc9555ff19fe3556aaa41c78a0a45c64d49ba2bc564507648a8e77a1', (select id from public.sources where url = 'https://www.seikowatches.com/us-en/products/presage/hcc004j1' and retrieved_at = '2026-08-29T08:35:05Z'::timestamptz),
  ps.observed_at, '2026-08-29T08:35:05Z'::timestamptz,
  '2026-08-29T08:35:05Z'::timestamptz,
  ps.stale_after, 'verified', 'catalogue-expansion-v1'
from public.price_snapshots ps
where ps.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1')
  and ps.kind = 'retail' and ps.condition = 'new'
  and ps.currency = 'USD'
  and ps.observed_at = '2026-08-29T08:35:05Z'::timestamptz
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, stale_after = excluded.stale_after,
  tier = 'verified', reviewer = 'catalogue-expansion-v1';



insert into public.completeness_evaluations (
  subject_type, subject_id, level, filter_contract_version, complete,
  completeness_score, missing_fields, evaluated_at
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'm0', 1,
  true, 1.0000, array[]::text[],
  '2026-08-29T08:35:05Z'::timestamptz
)
on conflict (subject_type, subject_id, level, filter_contract_version) do update set
  complete = excluded.complete,
  completeness_score = excluded.completeness_score,
  missing_fields = excluded.missing_fields,
  evaluated_at = excluded.evaluated_at;

insert into public.completeness_evaluations (
  subject_type, subject_id, level, filter_contract_version, complete,
  completeness_score, missing_fields, evaluated_at
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'm1', 1,
  true, 1.0000, array[]::text[],
  '2026-08-29T08:35:05Z'::timestamptz
)
on conflict (subject_type, subject_id, level, filter_contract_version) do update set
  complete = excluded.complete,
  completeness_score = excluded.completeness_score,
  missing_fields = excluded.missing_fields,
  evaluated_at = excluded.evaluated_at;

insert into public.completeness_evaluations (
  subject_type, subject_id, level, filter_contract_version, complete,
  completeness_score, missing_fields, evaluated_at
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'seiko' and rv.variant_key = 'seiko-hcc004j1'), 'm2', 1,
  false, 0.6667, array['market']::text[],
  '2026-08-29T08:35:05Z'::timestamptz
)
on conflict (subject_type, subject_id, level, filter_contract_version) do update set
  complete = excluded.complete,
  completeness_score = excluded.completeness_score,
  missing_fields = excluded.missing_fields,
  evaluated_at = excluded.evaluated_at;
