-- Generated by scripts/render-seed-migration.ts from the reviewed seed bundle.
-- Additive expansion for: luminox-leatherback-xs-0307-wo.

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.ronda.ch/en/watch-movement-finder/caliber/515', 'https://www.ronda.ch/en/watch-movement-finder/caliber/515', 'Ronda powertech shared 512/513/515 technical record', 'Ronda AG', 'manufacturer_data_sheet', '2026-08-30T21:42:16Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://ch.luminox.com/en/products/leatherback-sea-turtle-39-mm-outdoor-uhr-0307-wo', 'https://ch.luminox.com/en/products/leatherback-sea-turtle-39-mm-outdoor-uhr-0307-wo', 'Leatherback SEA Turtle 39 mm — XS.0307.WO', 'Luminox Switzerland', 'manufacturer_product', '2026-08-31T05:40:25Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.zegarki.zgora.pl/zegarek/24126_Luminox_Leatherback_Sea_Turtle_0300_Series_Whiteout_XS0307WO', 'https://www.zegarki.zgora.pl/zegarek/24126_Luminox_Leatherback_Sea_Turtle_0300_Series_Whiteout_XS0307WO', 'Luminox Leatherback SEA Turtle Whiteout XS.0307.WO', 'Zegarki Zielona Góra', 'secondary_editorial', '2026-08-31T05:40:25Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.auer.lu/en/luminox-leatherback-sea-turtle-swiss-carbon-watch-with-date-xs-0307-wo.htm', 'https://www.auer.lu/en/luminox-leatherback-sea-turtle-swiss-carbon-watch-with-date-xs-0307-wo.htm', 'Luminox XS.0307.WO exact interface specifications', 'Auer / Holland Watch Group', 'secondary_editorial', '2026-08-31T05:40:25Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.brands (slug, name, review_status)
values ('luminox', 'Luminox', 'accepted')
on conflict (slug) do update set name = excluded.name, review_status = 'accepted', updated_at = now();

insert into public.collections (brand_id, slug, name, review_status)
select id, 'leatherback-sea-turtle-0300-series', 'Leatherback SEA Turtle 0300 Series', 'accepted'
from public.brands where slug = 'luminox'
on conflict (brand_id, slug) do update set name = excluded.name, review_status = 'accepted', updated_at = now();

insert into public.reference_models (collection_id, slug, model_name, review_status)
select c.id, 'leatherback-sea-turtle', 'Leatherback SEA Turtle', 'accepted'
from public.collections c join public.brands b on b.id = c.brand_id
where b.slug = 'luminox' and c.slug = 'leatherback-sea-turtle-0300-series'
on conflict (collection_id, slug) do update set model_name = excluded.model_name, review_status = 'accepted', updated_at = now();

insert into public.reference_variants (
  reference_model_id, variant_key, reference_code, variant_name,
  case_material, caseback_material, bracelet_material, strap_material,
  nickel_contact_risk, case_diameter_mm, case_width_mm, case_length_mm,
  case_thickness_mm, lug_to_lug_mm,
  lug_to_lug_measured, lug_width_mm, lug_curvature, integrated_bracelet,
  weight_full_g, movement_type, caliber_ref, power_reserve_h,
  accuracy_lower_seconds, accuracy_upper_seconds, accuracy_period_days,
  water_resistance_m, crown_type, crown_position, crystal, lume_grade,
  bracelet_attachment, shock_resistant, production_status, review_status
)
values (
  (select rm.id from public.reference_models rm join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and c.slug = 'leatherback-sea-turtle-0300-series' and rm.slug = 'leatherback-sea-turtle'), 'luminox-leatherback-xs-0307-wo', 'XS.0307.WO', 'Whiteout dial and case · white silicone strap',
  'white fiberglass compound', '316L stainless steel screw-on caseback', null, 'white silicone',
  null, 39, null, null,
  12, 46,
  false, 19, null, false,
  48, 'quartz', 'Ronda 515', null,
  -10, 20, 30,
  100, 'push_pull', null, 'mineral', 'strong',
  'spring_bar', null, 'current', 'accepted'
)
on conflict (reference_model_id, variant_key) do update set
  reference_code = excluded.reference_code,
  variant_name = excluded.variant_name,
  case_material = excluded.case_material,
  caseback_material = excluded.caseback_material,
  bracelet_material = excluded.bracelet_material,
  strap_material = excluded.strap_material,
  nickel_contact_risk = excluded.nickel_contact_risk,
  case_diameter_mm = excluded.case_diameter_mm,
  case_width_mm = excluded.case_width_mm,
  case_length_mm = excluded.case_length_mm,
  case_thickness_mm = excluded.case_thickness_mm,
  lug_to_lug_mm = excluded.lug_to_lug_mm,
  lug_to_lug_measured = excluded.lug_to_lug_measured,
  lug_width_mm = excluded.lug_width_mm,
  lug_curvature = excluded.lug_curvature,
  integrated_bracelet = excluded.integrated_bracelet,
  weight_full_g = excluded.weight_full_g,
  movement_type = excluded.movement_type,
  caliber_ref = excluded.caliber_ref,
  power_reserve_h = excluded.power_reserve_h,
  accuracy_lower_seconds = excluded.accuracy_lower_seconds,
  accuracy_upper_seconds = excluded.accuracy_upper_seconds,
  accuracy_period_days = excluded.accuracy_period_days,
  water_resistance_m = excluded.water_resistance_m,
  crown_type = excluded.crown_type,
  crown_position = excluded.crown_position,
  crystal = excluded.crystal,
  lume_grade = excluded.lume_grade,
  bracelet_attachment = excluded.bracelet_attachment,
  shock_resistant = excluded.shock_resistant,
  production_status = excluded.production_status,
  review_status = 'accepted',
  updated_at = now();

update public.reference_variants
set product_url = 'https://ch.luminox.com/en/products/leatherback-sea-turtle-39-mm-outdoor-uhr-0307-wo', updated_at = now()
where id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo')
  and product_url is distinct from 'https://ch.luminox.com/en/products/leatherback-sea-turtle-39-mm-outdoor-uhr-0307-wo';

insert into public.reference_complications (reference_variant_id, complication)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'date')
on conflict (reference_variant_id, complication) do nothing;

insert into public.price_snapshots (
  reference_variant_id, kind, condition, currency, amount_low_minor,
  market_country_code, observed_at, stale_after, review_status
)
select (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'retail', 'new', 'PLN', 131500,
  'PL', '2026-08-31T05:40:25Z'::timestamptz, '2027-02-27T05:40:25Z'::timestamptz, 'accepted'
where not exists (
  select 1 from public.price_snapshots ps
  where ps.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo')
    and ps.kind = 'retail' and ps.condition = 'new'
    and ps.currency = 'PLN'
    and ps.observed_at = '2026-08-31T05:40:25Z'::timestamptz
);

insert into public.market_snapshots (
  reference_variant_id, market_country_code, availability, observed_at,
  stale_after, review_status
)
  select (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'PL', 'in_stock',
  '2026-08-31T05:40:25Z'::timestamptz,
  '2026-09-30T05:40:25Z'::timestamptz, 'accepted'
where not exists (
  select 1 from public.market_snapshots ms
  where ms.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo')
    and ms.market_country_code = 'PL'
    and ms.observed_at = '2026-08-31T05:40:25Z'::timestamptz
);

insert into public.reference_deployment_profiles (
  reference_variant_id, environment, review_status
)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'field_water_abuse', 'accepted')
on conflict (reference_variant_id, environment) do update set
  review_status = 'accepted';

insert into public.reference_deployment_profiles (
  reference_variant_id, environment, review_status
)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'studio_desk_daily', 'accepted')
on conflict (reference_variant_id, environment) do update set
  review_status = 'accepted';

insert into public.reference_ownership_friction_profiles (
  reference_variant_id, friction_level, review_status
)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'zero_maintenance', 'accepted')
on conflict (reference_variant_id, friction_level) do update set
  review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'primary_archetype', 'lightweight_tritium_field_quartz', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'social_signal', 'discreet_competence', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'aesthetic_dna', 'structural_tool', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'emotional_objective', 'dependability', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'identity', '2befff2e679a6dc75e1f7a832b1ffdbec654d84a571fb147b3a2b2348e66bfbc', (select id from public.sources where url = 'https://ch.luminox.com/en/products/leatherback-sea-turtle-39-mm-outdoor-uhr-0307-wo' and retrieved_at = '2026-08-31T05:40:25Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-31T05:40:25Z'::timestamptz,
  '2026-08-31T05:40:25Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'materials', '23821fffd8200fce905aec14677c96405b8bdaf729f3402c3b6949a630f34707', (select id from public.sources where url = 'https://ch.luminox.com/en/products/leatherback-sea-turtle-39-mm-outdoor-uhr-0307-wo' and retrieved_at = '2026-08-31T05:40:25Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-31T05:40:25Z'::timestamptz,
  '2026-08-31T05:40:25Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'productionStatus', '694df57a7909d9f9edbd3acb4ccfce5fbee156fab749383121f17fef16bbab57', (select id from public.sources where url = 'https://ch.luminox.com/en/products/leatherback-sea-turtle-39-mm-outdoor-uhr-0307-wo' and retrieved_at = '2026-08-31T05:40:25Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-31T05:40:25Z'::timestamptz,
  '2026-08-31T05:40:25Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'caseDiameterMm', '0b918943df0962bc7a1824c0555a389347b4febdc7cf9d1254406d80ce44e3f9', (select id from public.sources where url = 'https://ch.luminox.com/en/products/leatherback-sea-turtle-39-mm-outdoor-uhr-0307-wo' and retrieved_at = '2026-08-31T05:40:25Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-31T05:40:25Z'::timestamptz,
  '2026-08-31T05:40:25Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'caseThicknessMm', '6b51d431df5d7f141cbececcf79edf3dd861c3b4069f0b11661a3eefacbba918', (select id from public.sources where url = 'https://ch.luminox.com/en/products/leatherback-sea-turtle-39-mm-outdoor-uhr-0307-wo' and retrieved_at = '2026-08-31T05:40:25Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-31T05:40:25Z'::timestamptz,
  '2026-08-31T05:40:25Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'lugWidthMm', '9400f1b21cb527d7fa3d3eabba93557a18ebe7a2ca4e471cfe5e4c5b4ca7f767', (select id from public.sources where url = 'https://ch.luminox.com/en/products/leatherback-sea-turtle-39-mm-outdoor-uhr-0307-wo' and retrieved_at = '2026-08-31T05:40:25Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-31T05:40:25Z'::timestamptz,
  '2026-08-31T05:40:25Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'weightFullG', '98010bd9270f9b100b6214a21754fd33bdc8d41b2bc9f9dd16ff54d3c34ffd71', (select id from public.sources where url = 'https://ch.luminox.com/en/products/leatherback-sea-turtle-39-mm-outdoor-uhr-0307-wo' and retrieved_at = '2026-08-31T05:40:25Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-31T05:40:25Z'::timestamptz,
  '2026-08-31T05:40:25Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'movement', 'e147e5c214eec05b48d3625b35b996fdf7f590d6e76edca68b6c783c2d9552f1', (select id from public.sources where url = 'https://ch.luminox.com/en/products/leatherback-sea-turtle-39-mm-outdoor-uhr-0307-wo' and retrieved_at = '2026-08-31T05:40:25Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-31T05:40:25Z'::timestamptz,
  '2026-08-31T05:40:25Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'waterResistanceM', 'ad57366865126e55649ecb23ae1d48887544976efea46a48eb5d85a6eeb4d306', (select id from public.sources where url = 'https://ch.luminox.com/en/products/leatherback-sea-turtle-39-mm-outdoor-uhr-0307-wo' and retrieved_at = '2026-08-31T05:40:25Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-31T05:40:25Z'::timestamptz,
  '2026-08-31T05:40:25Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'crystal', '22c5534b9bb5b94643119966014b4f540e7ecd085c27a65061b52e313f357cd9', (select id from public.sources where url = 'https://ch.luminox.com/en/products/leatherback-sea-turtle-39-mm-outdoor-uhr-0307-wo' and retrieved_at = '2026-08-31T05:40:25Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-31T05:40:25Z'::timestamptz,
  '2026-08-31T05:40:25Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'lumeGrade', 'ec109d66b0e82ab98ada5f28fa8bf34dda5beff3f384e5f1a5f8bc2c3ba63a3c', (select id from public.sources where url = 'https://ch.luminox.com/en/products/leatherback-sea-turtle-39-mm-outdoor-uhr-0307-wo' and retrieved_at = '2026-08-31T05:40:25Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-31T05:40:25Z'::timestamptz,
  '2026-08-31T05:40:25Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'complications', '4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945', (select id from public.sources where url = 'https://ch.luminox.com/en/products/leatherback-sea-turtle-39-mm-outdoor-uhr-0307-wo' and retrieved_at = '2026-08-31T05:40:25Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-31T05:40:25Z'::timestamptz,
  '2026-08-31T05:40:25Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'dateStatus', '94332144d941eb1212c9af7f968e215a7042bf94925c9c10b21de97a2f0cea06', (select id from public.sources where url = 'https://ch.luminox.com/en/products/leatherback-sea-turtle-39-mm-outdoor-uhr-0307-wo' and retrieved_at = '2026-08-31T05:40:25Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-31T05:40:25Z'::timestamptz,
  '2026-08-31T05:40:25Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'eligibleEnvironments', 'b5781120ccbc8985769d931d5d6c17ee6d65b33500903d8820d7f0520f8e0a65', (select id from public.sources where url = 'https://ch.luminox.com/en/products/leatherback-sea-turtle-39-mm-outdoor-uhr-0307-wo' and retrieved_at = '2026-08-31T05:40:25Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-31T05:40:25Z'::timestamptz,
  '2026-08-31T05:40:25Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'ownershipFrictionLevels', 'e3c8833aa1e6b7e301cb9c74b3883b37ac16f6e3a73e83d8350c6b42f30775f3', (select id from public.sources where url = 'https://ch.luminox.com/en/products/leatherback-sea-turtle-39-mm-outdoor-uhr-0307-wo' and retrieved_at = '2026-08-31T05:40:25Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-31T05:40:25Z'::timestamptz,
  '2026-08-31T05:40:25Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'traits', '98f600facf0c96f0a834c9461a168fa03fb6b9e805f476c70c0bd35946cd8483', (select id from public.sources where url = 'https://ch.luminox.com/en/products/leatherback-sea-turtle-39-mm-outdoor-uhr-0307-wo' and retrieved_at = '2026-08-31T05:40:25Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-31T05:40:25Z'::timestamptz,
  '2026-08-31T05:40:25Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'identity', '2befff2e679a6dc75e1f7a832b1ffdbec654d84a571fb147b3a2b2348e66bfbc', (select id from public.sources where url = 'https://www.zegarki.zgora.pl/zegarek/24126_Luminox_Leatherback_Sea_Turtle_0300_Series_Whiteout_XS0307WO' and retrieved_at = '2026-08-31T05:40:25Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-31T05:40:25Z'::timestamptz,
  '2026-08-31T05:40:25Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'lugToLugMm', '25fc0e7096fc653718202dc30b0c580b8ab87eac11a700cba03a7c021bc35b0c', (select id from public.sources where url = 'https://www.zegarki.zgora.pl/zegarek/24126_Luminox_Leatherback_Sea_Turtle_0300_Series_Whiteout_XS0307WO' and retrieved_at = '2026-08-31T05:40:25Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-31T05:40:25Z'::timestamptz,
  '2026-08-31T05:40:25Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'identity', '2befff2e679a6dc75e1f7a832b1ffdbec654d84a571fb147b3a2b2348e66bfbc', (select id from public.sources where url = 'https://www.auer.lu/en/luminox-leatherback-sea-turtle-swiss-carbon-watch-with-date-xs-0307-wo.htm' and retrieved_at = '2026-08-31T05:40:25Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-31T05:40:25Z'::timestamptz,
  '2026-08-31T05:40:25Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'materials', '23821fffd8200fce905aec14677c96405b8bdaf729f3402c3b6949a630f34707', (select id from public.sources where url = 'https://www.auer.lu/en/luminox-leatherback-sea-turtle-swiss-carbon-watch-with-date-xs-0307-wo.htm' and retrieved_at = '2026-08-31T05:40:25Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-31T05:40:25Z'::timestamptz,
  '2026-08-31T05:40:25Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'integratedBracelet', 'fcbcf165908dd18a9e49f7ff27810176db8e9f63b4352213741664245224f8aa', (select id from public.sources where url = 'https://www.auer.lu/en/luminox-leatherback-sea-turtle-swiss-carbon-watch-with-date-xs-0307-wo.htm' and retrieved_at = '2026-08-31T05:40:25Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-31T05:40:25Z'::timestamptz,
  '2026-08-31T05:40:25Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'crownType', 'dfaa8e93fc07a2a9141ba5ebaa0c5335b0ca449b86ede61d274b5e63be301863', (select id from public.sources where url = 'https://www.auer.lu/en/luminox-leatherback-sea-turtle-swiss-carbon-watch-with-date-xs-0307-wo.htm' and retrieved_at = '2026-08-31T05:40:25Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-31T05:40:25Z'::timestamptz,
  '2026-08-31T05:40:25Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'crystal', '22c5534b9bb5b94643119966014b4f540e7ecd085c27a65061b52e313f357cd9', (select id from public.sources where url = 'https://www.auer.lu/en/luminox-leatherback-sea-turtle-swiss-carbon-watch-with-date-xs-0307-wo.htm' and retrieved_at = '2026-08-31T05:40:25Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-31T05:40:25Z'::timestamptz,
  '2026-08-31T05:40:25Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'attachmentType', 'dc8f261bad159c55d8fb5a6cdf75774951c242716e8306aaaad0e1a7b999db27', (select id from public.sources where url = 'https://www.auer.lu/en/luminox-leatherback-sea-turtle-swiss-carbon-watch-with-date-xs-0307-wo.htm' and retrieved_at = '2026-08-31T05:40:25Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-31T05:40:25Z'::timestamptz,
  '2026-08-31T05:40:25Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'dateStatus', '94332144d941eb1212c9af7f968e215a7042bf94925c9c10b21de97a2f0cea06', (select id from public.sources where url = 'https://www.auer.lu/en/luminox-leatherback-sea-turtle-swiss-carbon-watch-with-date-xs-0307-wo.htm' and retrieved_at = '2026-08-31T05:40:25Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-31T05:40:25Z'::timestamptz,
  '2026-08-31T05:40:25Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'movement', 'e147e5c214eec05b48d3625b35b996fdf7f590d6e76edca68b6c783c2d9552f1', (select id from public.sources where url = 'https://www.ronda.ch/en/watch-movement-finder/caliber/515' and retrieved_at = '2026-08-30T21:42:16Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-30T21:42:16Z'::timestamptz,
  '2026-08-30T21:42:16Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'accuracy', '84779b7ee5002046b3832c109beb876154ad5fb00898778f036a061d7e8f2aa8', (select id from public.sources where url = 'https://www.ronda.ch/en/watch-movement-finder/caliber/515' and retrieved_at = '2026-08-30T21:42:16Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-30T21:42:16Z'::timestamptz,
  '2026-08-30T21:42:16Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'dateStatus', '94332144d941eb1212c9af7f968e215a7042bf94925c9c10b21de97a2f0cea06', (select id from public.sources where url = 'https://www.ronda.ch/en/watch-movement-finder/caliber/515' and retrieved_at = '2026-08-30T21:42:16Z'::timestamptz),
  '2026-08-31T05:40:25Z'::timestamptz, '2026-08-30T21:42:16Z'::timestamptz,
  '2026-08-30T21:42:16Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';



insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, stale_after, tier, reviewer
)
select 'price_snapshot', ps.id, 'amount_low_minor', 'c15827ffe451e63bfd8958d898b6ec0b462932f179f5840a7296fcebd94af93c', (select id from public.sources where url = 'https://www.zegarki.zgora.pl/zegarek/24126_Luminox_Leatherback_Sea_Turtle_0300_Series_Whiteout_XS0307WO' and retrieved_at = '2026-08-31T05:40:25Z'::timestamptz),
  ps.observed_at, '2026-08-31T05:40:25Z'::timestamptz,
  '2026-08-31T05:40:25Z'::timestamptz,
  ps.stale_after, 'verified', 'catalogue-expansion-v1'
from public.price_snapshots ps
where ps.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo')
  and ps.kind = 'retail' and ps.condition = 'new'
  and ps.currency = 'PLN'
  and ps.observed_at = '2026-08-31T05:40:25Z'::timestamptz
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, stale_after = excluded.stale_after,
  tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, stale_after, tier, reviewer
)
select 'market_snapshot', ms.id, 'availability', 'a0d00556b975b95064b17e1539e14b4d7097a8121a370eab0bac44fe1eea8a10', (select id from public.sources where url = 'https://www.zegarki.zgora.pl/zegarek/24126_Luminox_Leatherback_Sea_Turtle_0300_Series_Whiteout_XS0307WO' and retrieved_at = '2026-08-31T05:40:25Z'::timestamptz),
  ms.observed_at, '2026-08-31T05:40:25Z'::timestamptz,
  '2026-08-31T05:40:25Z'::timestamptz,
  ms.stale_after, 'verified', 'catalogue-expansion-v1'
from public.market_snapshots ms
where ms.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo')
  and ms.market_country_code = 'PL'
  and ms.observed_at = '2026-08-31T05:40:25Z'::timestamptz
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, stale_after = excluded.stale_after,
  tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.completeness_evaluations (
  subject_type, subject_id, level, filter_contract_version, complete,
  completeness_score, missing_fields, evaluated_at
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'm0', 1,
  true, 1.0000, array[]::text[],
  '2026-08-31T05:40:25Z'::timestamptz
)
on conflict (subject_type, subject_id, level, filter_contract_version) do update set
  complete = excluded.complete,
  completeness_score = excluded.completeness_score,
  missing_fields = excluded.missing_fields,
  evaluated_at = excluded.evaluated_at;

insert into public.completeness_evaluations (
  subject_type, subject_id, level, filter_contract_version, complete,
  completeness_score, missing_fields, evaluated_at
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'm1', 1,
  true, 1.0000, array[]::text[],
  '2026-08-31T05:40:25Z'::timestamptz
)
on conflict (subject_type, subject_id, level, filter_contract_version) do update set
  complete = excluded.complete,
  completeness_score = excluded.completeness_score,
  missing_fields = excluded.missing_fields,
  evaluated_at = excluded.evaluated_at;

insert into public.completeness_evaluations (
  subject_type, subject_id, level, filter_contract_version, complete,
  completeness_score, missing_fields, evaluated_at
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'luminox' and rv.variant_key = 'luminox-leatherback-xs-0307-wo'), 'm2', 1,
  false, 0.6667, array['market']::text[],
  '2026-08-31T05:40:25Z'::timestamptz
)
on conflict (subject_type, subject_id, level, filter_contract_version) do update set
  complete = excluded.complete,
  completeness_score = excluded.completeness_score,
  missing_fields = excluded.missing_fields,
  evaluated_at = excluded.evaluated_at;
