-- Generated by scripts/render-seed-migration.ts from the reviewed seed bundle.
-- Additive expansion for: laco-augsburg-39-861988.

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.laco.de/en/watches/pilot-watches-basic/augsburg-39/861988', 'https://www.laco.de/en/watches/pilot-watches-basic/augsburg-39/861988', 'Pilot Watch Augsburg 39 — article 861988', 'Laco Uhrenmanufaktur', 'manufacturer_product', '2026-08-30T19:57:59Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.laco.de/en/faq', 'https://www.laco.de/en/faq', 'LACO 2S regulation and power-reserve specification', 'Laco Uhrenmanufaktur', 'manufacturer_data_sheet', '2026-08-30T19:57:59Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://miyotamovement.com/product/82S0/', 'https://miyotamovement.com/product/82S0/', 'Miyota calibre 82S0 specification', 'Citizen Watch Co. / Miyota', 'manufacturer_data_sheet', '2026-08-30T19:57:59Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.laco.de/media/85/ed/8d/1755689521/11_3_Gebrauchsanweisung_Laco_Lederbaender.pdf?ts=1755689521', 'https://www.laco.de/media/85/ed/8d/1755689521/11_3_Gebrauchsanweisung_Laco_Lederbaender.pdf?ts=1755689521', 'Laco leather watch strap instructions', 'Laco Uhrenmanufaktur', 'manufacturer_manual', '2026-08-30T19:57:59Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.trustedshops.de/bewertung/info_XA22FF9B21733A0EAC7FC18702C984C3E.html', 'https://www.trustedshops.de/bewertung/info_XA22FF9B21733A0EAC7FC18702C984C3E.html', 'Verified Augsburg 39 owner review and Laco response', 'Trusted Shops / Laco Uhrenmanufaktur', 'secondary_editorial', '2026-08-31T06:08:07Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.brands (slug, name, review_status)
values ('laco', 'Laco', 'accepted')
on conflict (slug) do update set name = excluded.name, review_status = 'accepted', updated_at = now();

insert into public.collections (brand_id, slug, name, review_status)
select id, 'pilot-watches-basic', 'Pilot Watches Basic', 'accepted'
from public.brands where slug = 'laco'
on conflict (brand_id, slug) do update set name = excluded.name, review_status = 'accepted', updated_at = now();

insert into public.reference_models (collection_id, slug, model_name, review_status)
select c.id, 'augsburg-39', 'Augsburg 39', 'accepted'
from public.collections c join public.brands b on b.id = c.brand_id
where b.slug = 'laco' and c.slug = 'pilot-watches-basic'
on conflict (collection_id, slug) do update set model_name = excluded.model_name, review_status = 'accepted', updated_at = now();

insert into public.reference_variants (
  reference_model_id, variant_key, reference_code, variant_name,
  case_material, caseback_material, bracelet_material, strap_material,
  nickel_contact_risk, case_diameter_mm, case_width_mm, case_length_mm,
  case_thickness_mm, lug_to_lug_mm,
  lug_to_lug_measured, lug_width_mm, lug_curvature, integrated_bracelet,
  weight_full_g, movement_type, caliber_ref, power_reserve_h,
  accuracy_lower_seconds, accuracy_upper_seconds, accuracy_period_days,
  water_resistance_m, crown_type, crown_position, crystal, lume_grade,
  bracelet_attachment, shock_resistant, production_status, review_status
)
values (
  (select rm.id from public.reference_models rm join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and c.slug = 'pilot-watches-basic' and rm.slug = 'augsburg-39'), 'laco-augsburg-39-861988', '861988', 'Black dial · brown riveted calf-leather strap',
  'sandblasted stainless steel', 'stainless steel with sapphire crystal display back', null, 'brown riveted calf leather',
  null, 39, null, null,
  11.55, 46.5,
  false, 18, null, false,
  81.5, 'automatic', 'LACO 2S (Miyota 82S0 base)', 42,
  0, 25, 1,
  50, null, null, 'sapphire', 'strong',
  'spring_bar', null, 'current', 'accepted'
)
on conflict (reference_model_id, variant_key) do update set
  reference_code = excluded.reference_code,
  variant_name = excluded.variant_name,
  case_material = excluded.case_material,
  caseback_material = excluded.caseback_material,
  bracelet_material = excluded.bracelet_material,
  strap_material = excluded.strap_material,
  nickel_contact_risk = excluded.nickel_contact_risk,
  case_diameter_mm = excluded.case_diameter_mm,
  case_width_mm = excluded.case_width_mm,
  case_length_mm = excluded.case_length_mm,
  case_thickness_mm = excluded.case_thickness_mm,
  lug_to_lug_mm = excluded.lug_to_lug_mm,
  lug_to_lug_measured = excluded.lug_to_lug_measured,
  lug_width_mm = excluded.lug_width_mm,
  lug_curvature = excluded.lug_curvature,
  integrated_bracelet = excluded.integrated_bracelet,
  weight_full_g = excluded.weight_full_g,
  movement_type = excluded.movement_type,
  caliber_ref = excluded.caliber_ref,
  power_reserve_h = excluded.power_reserve_h,
  accuracy_lower_seconds = excluded.accuracy_lower_seconds,
  accuracy_upper_seconds = excluded.accuracy_upper_seconds,
  accuracy_period_days = excluded.accuracy_period_days,
  water_resistance_m = excluded.water_resistance_m,
  crown_type = excluded.crown_type,
  crown_position = excluded.crown_position,
  crystal = excluded.crystal,
  lume_grade = excluded.lume_grade,
  bracelet_attachment = excluded.bracelet_attachment,
  shock_resistant = excluded.shock_resistant,
  production_status = excluded.production_status,
  review_status = 'accepted',
  updated_at = now();

update public.reference_variants
set product_url = 'https://www.laco.de/en/watches/pilot-watches-basic/augsburg-39/861988', updated_at = now()
where id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988')
  and product_url is distinct from 'https://www.laco.de/en/watches/pilot-watches-basic/augsburg-39/861988';



insert into public.price_snapshots (
  reference_variant_id, kind, condition, currency, amount_low_minor,
  market_country_code, observed_at, stale_after, review_status
)
select (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'retail', 'new', 'EUR', 39000,
  'DE', '2026-08-30T19:57:59Z'::timestamptz, '2027-02-26T19:57:59Z'::timestamptz, 'accepted'
where not exists (
  select 1 from public.price_snapshots ps
  where ps.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988')
    and ps.kind = 'retail' and ps.condition = 'new'
    and ps.currency = 'EUR'
    and ps.observed_at = '2026-08-30T19:57:59Z'::timestamptz
);

insert into public.market_snapshots (
  reference_variant_id, market_country_code, availability, observed_at,
  stale_after, review_status
)
  select (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'DE', 'in_stock',
  '2026-08-30T19:57:59Z'::timestamptz,
  '2026-09-29T19:57:59Z'::timestamptz, 'accepted'
where not exists (
  select 1 from public.market_snapshots ms
  where ms.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988')
    and ms.market_country_code = 'DE'
    and ms.observed_at = '2026-08-30T19:57:59Z'::timestamptz
);

insert into public.reference_deployment_profiles (
  reference_variant_id, environment, review_status
)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'studio_desk_daily', 'accepted')
on conflict (reference_variant_id, environment) do update set
  review_status = 'accepted';

insert into public.reference_ownership_friction_profiles (
  reference_variant_id, friction_level, review_status
)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'workhorse_mechanical', 'accepted')
on conflict (reference_variant_id, friction_level) do update set
  review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'primary_archetype', 'compact_pilot_instrument', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'social_signal', 'quiet_continuity', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'aesthetic_dna', 'structural_tool', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'emotional_objective', 'dependability', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'identity', 'db4fd665f094e84c5f2b1602ff97bb5e2b58eb4944e62be4fde89cf12b387d7c', (select id from public.sources where url = 'https://www.laco.de/en/watches/pilot-watches-basic/augsburg-39/861988' and retrieved_at = '2026-08-30T19:57:59Z'::timestamptz),
  '2026-08-30T19:57:59Z'::timestamptz, '2026-08-30T19:57:59Z'::timestamptz,
  '2026-08-30T19:57:59Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'materials', 'efc1ade409a99738f08ea160fc9ef9334dac08e860ae7cfc5aaf14c43316f4fe', (select id from public.sources where url = 'https://www.laco.de/en/watches/pilot-watches-basic/augsburg-39/861988' and retrieved_at = '2026-08-30T19:57:59Z'::timestamptz),
  '2026-08-30T19:57:59Z'::timestamptz, '2026-08-30T19:57:59Z'::timestamptz,
  '2026-08-30T19:57:59Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'productionStatus', '694df57a7909d9f9edbd3acb4ccfce5fbee156fab749383121f17fef16bbab57', (select id from public.sources where url = 'https://www.laco.de/en/watches/pilot-watches-basic/augsburg-39/861988' and retrieved_at = '2026-08-30T19:57:59Z'::timestamptz),
  '2026-08-30T19:57:59Z'::timestamptz, '2026-08-30T19:57:59Z'::timestamptz,
  '2026-08-30T19:57:59Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'caseDiameterMm', '0b918943df0962bc7a1824c0555a389347b4febdc7cf9d1254406d80ce44e3f9', (select id from public.sources where url = 'https://www.laco.de/en/watches/pilot-watches-basic/augsburg-39/861988' and retrieved_at = '2026-08-30T19:57:59Z'::timestamptz),
  '2026-08-30T19:57:59Z'::timestamptz, '2026-08-30T19:57:59Z'::timestamptz,
  '2026-08-30T19:57:59Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'caseThicknessMm', '85912e25c1fec9090f706ca9c680248247252ef977e27c991130efb96c99948d', (select id from public.sources where url = 'https://www.laco.de/en/watches/pilot-watches-basic/augsburg-39/861988' and retrieved_at = '2026-08-30T19:57:59Z'::timestamptz),
  '2026-08-30T19:57:59Z'::timestamptz, '2026-08-30T19:57:59Z'::timestamptz,
  '2026-08-30T19:57:59Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'lugToLugMm', '3c09fb8a4099861fb6c3d08e4eae2f7659770fa238d1204a3bd0f3d520b4d487', (select id from public.sources where url = 'https://www.laco.de/en/watches/pilot-watches-basic/augsburg-39/861988' and retrieved_at = '2026-08-30T19:57:59Z'::timestamptz),
  '2026-08-30T19:57:59Z'::timestamptz, '2026-08-30T19:57:59Z'::timestamptz,
  '2026-08-30T19:57:59Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'lugWidthMm', '4ec9599fc203d176a301536c2e091a19bc852759b255bd6818810a42c5fed14a', (select id from public.sources where url = 'https://www.laco.de/en/watches/pilot-watches-basic/augsburg-39/861988' and retrieved_at = '2026-08-30T19:57:59Z'::timestamptz),
  '2026-08-30T19:57:59Z'::timestamptz, '2026-08-30T19:57:59Z'::timestamptz,
  '2026-08-30T19:57:59Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'weightFullG', '14037437767a8c9fd500d2db953adc38d0d128b9ef5c0c248e427e61b3259eba', (select id from public.sources where url = 'https://www.laco.de/en/watches/pilot-watches-basic/augsburg-39/861988' and retrieved_at = '2026-08-30T19:57:59Z'::timestamptz),
  '2026-08-30T19:57:59Z'::timestamptz, '2026-08-30T19:57:59Z'::timestamptz,
  '2026-08-30T19:57:59Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'movement', '4fa7809d87c9d8fd77aaaf0fc59901dea6a52d8382343d2e551d807be75c7786', (select id from public.sources where url = 'https://www.laco.de/en/watches/pilot-watches-basic/augsburg-39/861988' and retrieved_at = '2026-08-30T19:57:59Z'::timestamptz),
  '2026-08-30T19:57:59Z'::timestamptz, '2026-08-30T19:57:59Z'::timestamptz,
  '2026-08-30T19:57:59Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'waterResistanceM', '1a6562590ef19d1045d06c4055742d38288e9e6dcd71ccde5cee80f1d5a774eb', (select id from public.sources where url = 'https://www.laco.de/en/watches/pilot-watches-basic/augsburg-39/861988' and retrieved_at = '2026-08-30T19:57:59Z'::timestamptz),
  '2026-08-30T19:57:59Z'::timestamptz, '2026-08-30T19:57:59Z'::timestamptz,
  '2026-08-30T19:57:59Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'crystal', '7191152669ad73162c786dd51b4301ac95d94e7b053dea5f698bd2815785cfef', (select id from public.sources where url = 'https://www.laco.de/en/watches/pilot-watches-basic/augsburg-39/861988' and retrieved_at = '2026-08-30T19:57:59Z'::timestamptz),
  '2026-08-30T19:57:59Z'::timestamptz, '2026-08-30T19:57:59Z'::timestamptz,
  '2026-08-30T19:57:59Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'eligibleEnvironments', 'fbb0b924881a24c74e2267336a9b012639bf5ef76f997be67ed98ebac888284b', (select id from public.sources where url = 'https://www.laco.de/en/watches/pilot-watches-basic/augsburg-39/861988' and retrieved_at = '2026-08-30T19:57:59Z'::timestamptz),
  '2026-08-30T19:57:59Z'::timestamptz, '2026-08-30T19:57:59Z'::timestamptz,
  '2026-08-30T19:57:59Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'ownershipFrictionLevels', '582066aec46a0e953a89b01aca2612ef776f66237e411fec8fb5f77652aaee62', (select id from public.sources where url = 'https://www.laco.de/en/watches/pilot-watches-basic/augsburg-39/861988' and retrieved_at = '2026-08-30T19:57:59Z'::timestamptz),
  '2026-08-30T19:57:59Z'::timestamptz, '2026-08-30T19:57:59Z'::timestamptz,
  '2026-08-30T19:57:59Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'traits', '7ccd13a6a996096a24913c1c844b2f52eb58a57f8e2ec27c5d65c62ebee161b5', (select id from public.sources where url = 'https://www.laco.de/en/watches/pilot-watches-basic/augsburg-39/861988' and retrieved_at = '2026-08-30T19:57:59Z'::timestamptz),
  '2026-08-30T19:57:59Z'::timestamptz, '2026-08-30T19:57:59Z'::timestamptz,
  '2026-08-30T19:57:59Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'movement', '4fa7809d87c9d8fd77aaaf0fc59901dea6a52d8382343d2e551d807be75c7786', (select id from public.sources where url = 'https://www.laco.de/en/faq' and retrieved_at = '2026-08-30T19:57:59Z'::timestamptz),
  '2026-08-30T19:57:59Z'::timestamptz, '2026-08-30T19:57:59Z'::timestamptz,
  '2026-08-30T19:57:59Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'accuracy', '4751892a36b8d1833b84d7f0651e5be3038e403abe46ee9be8cf9bfa48e0ac90', (select id from public.sources where url = 'https://www.laco.de/en/faq' and retrieved_at = '2026-08-30T19:57:59Z'::timestamptz),
  '2026-08-30T19:57:59Z'::timestamptz, '2026-08-30T19:57:59Z'::timestamptz,
  '2026-08-30T19:57:59Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'movement', '4fa7809d87c9d8fd77aaaf0fc59901dea6a52d8382343d2e551d807be75c7786', (select id from public.sources where url = 'https://miyotamovement.com/product/82S0/' and retrieved_at = '2026-08-30T19:57:59Z'::timestamptz),
  '2026-08-30T19:57:59Z'::timestamptz, '2026-08-30T19:57:59Z'::timestamptz,
  '2026-08-30T19:57:59Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'complications', '4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945', (select id from public.sources where url = 'https://miyotamovement.com/product/82S0/' and retrieved_at = '2026-08-30T19:57:59Z'::timestamptz),
  '2026-08-30T19:57:59Z'::timestamptz, '2026-08-30T19:57:59Z'::timestamptz,
  '2026-08-30T19:57:59Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'dateStatus', '15dbb2c4361b809a46b847b3b6c071f3c27c096057d31c45351902b79fe39efd', (select id from public.sources where url = 'https://miyotamovement.com/product/82S0/' and retrieved_at = '2026-08-30T19:57:59Z'::timestamptz),
  '2026-08-30T19:57:59Z'::timestamptz, '2026-08-30T19:57:59Z'::timestamptz,
  '2026-08-30T19:57:59Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'integratedBracelet', 'fcbcf165908dd18a9e49f7ff27810176db8e9f63b4352213741664245224f8aa', (select id from public.sources where url = 'https://www.laco.de/media/85/ed/8d/1755689521/11_3_Gebrauchsanweisung_Laco_Lederbaender.pdf?ts=1755689521' and retrieved_at = '2026-08-30T19:57:59Z'::timestamptz),
  '2026-08-30T19:57:59Z'::timestamptz, '2026-08-30T19:57:59Z'::timestamptz,
  '2026-08-30T19:57:59Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'attachmentType', 'dc8f261bad159c55d8fb5a6cdf75774951c242716e8306aaaad0e1a7b999db27', (select id from public.sources where url = 'https://www.laco.de/media/85/ed/8d/1755689521/11_3_Gebrauchsanweisung_Laco_Lederbaender.pdf?ts=1755689521' and retrieved_at = '2026-08-30T19:57:59Z'::timestamptz),
  '2026-08-30T19:57:59Z'::timestamptz, '2026-08-30T19:57:59Z'::timestamptz,
  '2026-08-30T19:57:59Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'identity', 'db4fd665f094e84c5f2b1602ff97bb5e2b58eb4944e62be4fde89cf12b387d7c', (select id from public.sources where url = 'https://www.trustedshops.de/bewertung/info_XA22FF9B21733A0EAC7FC18702C984C3E.html' and retrieved_at = '2026-08-31T06:08:07Z'::timestamptz),
  '2026-08-30T19:57:59Z'::timestamptz, '2026-08-31T06:08:07Z'::timestamptz,
  '2026-08-31T06:08:07Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'lumeGrade', 'ec109d66b0e82ab98ada5f28fa8bf34dda5beff3f384e5f1a5f8bc2c3ba63a3c', (select id from public.sources where url = 'https://www.trustedshops.de/bewertung/info_XA22FF9B21733A0EAC7FC18702C984C3E.html' and retrieved_at = '2026-08-31T06:08:07Z'::timestamptz),
  '2026-08-30T19:57:59Z'::timestamptz, '2026-08-31T06:08:07Z'::timestamptz,
  '2026-08-31T06:08:07Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';



insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, stale_after, tier, reviewer
)
select 'price_snapshot', ps.id, 'amount_low_minor', 'f1209245e37c7741cde83fe802f71e65480056593ea211fcff72ae48025bd754', (select id from public.sources where url = 'https://www.laco.de/en/watches/pilot-watches-basic/augsburg-39/861988' and retrieved_at = '2026-08-30T19:57:59Z'::timestamptz),
  ps.observed_at, '2026-08-30T19:57:59Z'::timestamptz,
  '2026-08-30T19:57:59Z'::timestamptz,
  ps.stale_after, 'verified', 'catalogue-expansion-v1'
from public.price_snapshots ps
where ps.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988')
  and ps.kind = 'retail' and ps.condition = 'new'
  and ps.currency = 'EUR'
  and ps.observed_at = '2026-08-30T19:57:59Z'::timestamptz
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, stale_after = excluded.stale_after,
  tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, stale_after, tier, reviewer
)
select 'market_snapshot', ms.id, 'availability', 'a0d00556b975b95064b17e1539e14b4d7097a8121a370eab0bac44fe1eea8a10', (select id from public.sources where url = 'https://www.laco.de/en/watches/pilot-watches-basic/augsburg-39/861988' and retrieved_at = '2026-08-30T19:57:59Z'::timestamptz),
  ms.observed_at, '2026-08-30T19:57:59Z'::timestamptz,
  '2026-08-30T19:57:59Z'::timestamptz,
  ms.stale_after, 'verified', 'catalogue-expansion-v1'
from public.market_snapshots ms
where ms.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988')
  and ms.market_country_code = 'DE'
  and ms.observed_at = '2026-08-30T19:57:59Z'::timestamptz
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, stale_after = excluded.stale_after,
  tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.completeness_evaluations (
  subject_type, subject_id, level, filter_contract_version, complete,
  completeness_score, missing_fields, evaluated_at
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'm0', 1,
  true, 1.0000, array[]::text[],
  '2026-08-30T19:57:59Z'::timestamptz
)
on conflict (subject_type, subject_id, level, filter_contract_version) do update set
  complete = excluded.complete,
  completeness_score = excluded.completeness_score,
  missing_fields = excluded.missing_fields,
  evaluated_at = excluded.evaluated_at;

insert into public.completeness_evaluations (
  subject_type, subject_id, level, filter_contract_version, complete,
  completeness_score, missing_fields, evaluated_at
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'm1', 1,
  true, 1.0000, array[]::text[],
  '2026-08-30T19:57:59Z'::timestamptz
)
on conflict (subject_type, subject_id, level, filter_contract_version) do update set
  complete = excluded.complete,
  completeness_score = excluded.completeness_score,
  missing_fields = excluded.missing_fields,
  evaluated_at = excluded.evaluated_at;

insert into public.completeness_evaluations (
  subject_type, subject_id, level, filter_contract_version, complete,
  completeness_score, missing_fields, evaluated_at
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'laco' and rv.variant_key = 'laco-augsburg-39-861988'), 'm2', 1,
  false, 0.6667, array['market']::text[],
  '2026-08-30T19:57:59Z'::timestamptz
)
on conflict (subject_type, subject_id, level, filter_contract_version) do update set
  complete = excluded.complete,
  completeness_score = excluded.completeness_score,
  missing_fields = excluded.missing_fields,
  evaluated_at = excluded.evaluated_at;
