-- Generated by scripts/render-seed-migration.ts from the reviewed seed bundle.
-- Additive expansion for: vostok-europe-vk61-571h614.

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://vostok-europe.com/product/vk61-571h614', 'https://vostok-europe.com/product/vk61-571h614', 'Nuclear Submarine SSN 571 — VK61-571H614', 'Vostok Europe', 'manufacturer_product', '2026-08-30T19:32:02Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.vostok-europe.com/public/vendor/laravel-files/files/manuals-catalogues/ve-catalog-2024.pdf', 'https://www.vostok-europe.com/public/vendor/laravel-files/files/manuals-catalogues/ve-catalog-2024.pdf', 'Vostok Europe 2024 catalogue', 'Vostok Europe', 'manufacturer_data_sheet', '2026-08-30T19:32:02Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://vostok-europe.com/vendor/laravel-files/files/manuals-catalogues/new-2026/ve-users-guide-auto-en.pdf', 'https://vostok-europe.com/vendor/laravel-files/files/manuals-catalogues/new-2026/ve-users-guide-auto-en.pdf', 'Vostok Europe screw-fixed strap user guide', 'Vostok Europe', 'manufacturer_manual', '2026-08-30T19:32:02Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://vostok-europe.com/archive', 'https://vostok-europe.com/archive', 'Vostok Europe legacy-product archive', 'Vostok Europe', 'manufacturer_product', '2026-08-30T19:32:02Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.zlatnictvinoemi.cz/hodinky-vostok-europe-ssn571-nuclear-submarine-chrono-line-titanium-vk61-571h614-darek-zdarma', 'https://www.zlatnictvinoemi.cz/hodinky-vostok-europe-ssn571-nuclear-submarine-chrono-line-titanium-vk61-571h614-darek-zdarma', 'Vostok Europe SSN 571 VK61-571H614 Czech offer', 'Zlatnictvi Noemi', 'secondary_editorial', '2026-08-30T19:32:02Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.otto.de/p/vostok-europe-chronograph-nuclear-submarine-herrneuhr-vk61-571h614-lederband-46-mm-CS071P09T/', 'https://www.otto.de/p/vostok-europe-chronograph-nuclear-submarine-herrneuhr-vk61-571h614-lederband-46-mm-CS071P09T/', 'VK61-571H614 leather configuration and full weight', 'OTTO', 'secondary_editorial', '2026-08-31T06:19:09Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.brands (slug, name, review_status)
values ('vostok-europe', 'Vostok Europe', 'accepted')
on conflict (slug) do update set name = excluded.name, review_status = 'accepted', updated_at = now();

insert into public.collections (brand_id, slug, name, review_status)
select id, 'nuclear-submarine-ssn-571', 'Nuclear Submarine SSN 571', 'accepted'
from public.brands where slug = 'vostok-europe'
on conflict (brand_id, slug) do update set name = excluded.name, review_status = 'accepted', updated_at = now();

insert into public.reference_models (collection_id, slug, model_name, review_status)
select c.id, 'nuclear-submarine-ssn-571', 'Nuclear Submarine SSN 571', 'accepted'
from public.collections c join public.brands b on b.id = c.brand_id
where b.slug = 'vostok-europe' and c.slug = 'nuclear-submarine-ssn-571'
on conflict (collection_id, slug) do update set model_name = excluded.model_name, review_status = 'accepted', updated_at = now();

insert into public.reference_variants (
  reference_model_id, variant_key, reference_code, variant_name,
  case_material, caseback_material, bracelet_material, strap_material,
  nickel_contact_risk, case_diameter_mm, case_width_mm, case_length_mm,
  case_thickness_mm, lug_to_lug_mm,
  lug_to_lug_measured, lug_width_mm, lug_curvature, integrated_bracelet,
  weight_full_g, movement_type, caliber_ref, power_reserve_h,
  accuracy_lower_seconds, accuracy_upper_seconds, accuracy_period_days,
  water_resistance_m, crown_type, crown_position, crystal, lume_grade,
  bracelet_attachment, shock_resistant, production_status, review_status
)
values (
  (select rm.id from public.reference_models rm join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and c.slug = 'nuclear-submarine-ssn-571' and rm.slug = 'nuclear-submarine-ssn-571'), 'vostok-europe-vk61-571h614', 'VK61-571H614', 'Titanium case on black leather strap with petrol stitching; black silicone accessory strap included',
  'titanium', 'titanium screw-down caseback', null, 'black leather with petrol contrast stitching',
  null, 45.7, null, null,
  15.6, 56.2,
  false, 22, null, false,
  135, 'hybrid', 'TMI VK61A', null,
  -20, 20, 30,
  300, 'screw_down', null, 'mineral', 'strong',
  'proprietary', null, 'discontinued', 'accepted'
)
on conflict (reference_model_id, variant_key) do update set
  reference_code = excluded.reference_code,
  variant_name = excluded.variant_name,
  case_material = excluded.case_material,
  caseback_material = excluded.caseback_material,
  bracelet_material = excluded.bracelet_material,
  strap_material = excluded.strap_material,
  nickel_contact_risk = excluded.nickel_contact_risk,
  case_diameter_mm = excluded.case_diameter_mm,
  case_width_mm = excluded.case_width_mm,
  case_length_mm = excluded.case_length_mm,
  case_thickness_mm = excluded.case_thickness_mm,
  lug_to_lug_mm = excluded.lug_to_lug_mm,
  lug_to_lug_measured = excluded.lug_to_lug_measured,
  lug_width_mm = excluded.lug_width_mm,
  lug_curvature = excluded.lug_curvature,
  integrated_bracelet = excluded.integrated_bracelet,
  weight_full_g = excluded.weight_full_g,
  movement_type = excluded.movement_type,
  caliber_ref = excluded.caliber_ref,
  power_reserve_h = excluded.power_reserve_h,
  accuracy_lower_seconds = excluded.accuracy_lower_seconds,
  accuracy_upper_seconds = excluded.accuracy_upper_seconds,
  accuracy_period_days = excluded.accuracy_period_days,
  water_resistance_m = excluded.water_resistance_m,
  crown_type = excluded.crown_type,
  crown_position = excluded.crown_position,
  crystal = excluded.crystal,
  lume_grade = excluded.lume_grade,
  bracelet_attachment = excluded.bracelet_attachment,
  shock_resistant = excluded.shock_resistant,
  production_status = excluded.production_status,
  review_status = 'accepted',
  updated_at = now();

update public.reference_variants
set product_url = 'https://vostok-europe.com/product/vk61-571h614', updated_at = now()
where id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614')
  and product_url is distinct from 'https://vostok-europe.com/product/vk61-571h614';

insert into public.reference_complications (reference_variant_id, complication)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'chronograph')
on conflict (reference_variant_id, complication) do nothing;

insert into public.reference_complications (reference_variant_id, complication)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'date')
on conflict (reference_variant_id, complication) do nothing;

insert into public.price_snapshots (
  reference_variant_id, kind, condition, currency, amount_low_minor,
  market_country_code, observed_at, stale_after, review_status
)
select (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'retail', 'new', 'EUR', 79300,
  'CZ', '2026-08-30T19:32:02Z'::timestamptz, '2027-02-26T19:32:02Z'::timestamptz, 'accepted'
where not exists (
  select 1 from public.price_snapshots ps
  where ps.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614')
    and ps.kind = 'retail' and ps.condition = 'new'
    and ps.currency = 'EUR'
    and ps.observed_at = '2026-08-30T19:32:02Z'::timestamptz
);

insert into public.market_snapshots (
  reference_variant_id, market_country_code, availability, observed_at,
  stale_after, review_status
)
  select (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'CZ', 'partial_waitlist',
  '2026-08-30T19:32:02Z'::timestamptz,
  '2026-09-29T19:32:02Z'::timestamptz, 'accepted'
where not exists (
  select 1 from public.market_snapshots ms
  where ms.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614')
    and ms.market_country_code = 'CZ'
    and ms.observed_at = '2026-08-30T19:32:02Z'::timestamptz
);

insert into public.reference_deployment_profiles (
  reference_variant_id, environment, review_status
)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'field_water_abuse', 'accepted')
on conflict (reference_variant_id, environment) do update set
  review_status = 'accepted';

insert into public.reference_deployment_profiles (
  reference_variant_id, environment, review_status
)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'studio_desk_daily', 'accepted')
on conflict (reference_variant_id, environment) do update set
  review_status = 'accepted';

insert into public.reference_ownership_friction_profiles (
  reference_variant_id, friction_level, review_status
)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'zero_maintenance', 'accepted')
on conflict (reference_variant_id, friction_level) do update set
  review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'primary_archetype', 'titanium_tritium_meca_quartz_chronograph', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'social_signal', 'unapologetic_benchmark', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'aesthetic_dna', 'structural_tool', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'emotional_objective', 'dependability', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'emotional_objective', 'differentiation', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'identity', '13afc6f4332cd23783976ae8ce697afbc3b5713cca7328adc4a4cf616b7ec389', (select id from public.sources where url = 'https://vostok-europe.com/product/vk61-571h614' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'materials', 'dfd018b406ec3af78de467f8460551487a5915fe3b9d166f3905b0bfcdbeda8f', (select id from public.sources where url = 'https://vostok-europe.com/product/vk61-571h614' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'caseDiameterMm', 'fce5e64959fa46a4fe17a531c9a4e9186617055c844ce1c885b58aa6f1ac2a79', (select id from public.sources where url = 'https://vostok-europe.com/product/vk61-571h614' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'caseThicknessMm', 'dabbeb4a53d00ef7cb490aa9dbb72291e285128eba198151a954287e42afa927', (select id from public.sources where url = 'https://vostok-europe.com/product/vk61-571h614' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'lugToLugMm', '9d6f07dbac9ef9bf6ad587187dd1be901b66bfa203aae189518a63966c5c6140', (select id from public.sources where url = 'https://vostok-europe.com/product/vk61-571h614' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'lugWidthMm', '785f3ec7eb32f30b90cd0fcf3657d388b5ff4297f2f9716ff66e9b69c05ddd09', (select id from public.sources where url = 'https://vostok-europe.com/product/vk61-571h614' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'movement', 'b051183eb452d792a8b72b7ad5b3129a79d20cb61b0f4b23cff5d3f10b233c96', (select id from public.sources where url = 'https://vostok-europe.com/product/vk61-571h614' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'waterResistanceM', '983bd614bb5afece5ab3b6023f71147cd7b6bc2314f9d27af7422541c6558389', (select id from public.sources where url = 'https://vostok-europe.com/product/vk61-571h614' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'crownType', '2026fa400c91bf0e5fd82a1b3b951961bbb0fd2f862c4142a26aa6d59e82ce34', (select id from public.sources where url = 'https://vostok-europe.com/product/vk61-571h614' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'crystal', '22c5534b9bb5b94643119966014b4f540e7ecd085c27a65061b52e313f357cd9', (select id from public.sources where url = 'https://vostok-europe.com/product/vk61-571h614' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'lumeGrade', 'ec109d66b0e82ab98ada5f28fa8bf34dda5beff3f384e5f1a5f8bc2c3ba63a3c', (select id from public.sources where url = 'https://vostok-europe.com/product/vk61-571h614' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'complications', 'e6b33e79c0e003ac264d4a6f7f310d08ded731d3c8a0c942db8288a6e8b50d87', (select id from public.sources where url = 'https://vostok-europe.com/product/vk61-571h614' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'dateStatus', '94332144d941eb1212c9af7f968e215a7042bf94925c9c10b21de97a2f0cea06', (select id from public.sources where url = 'https://vostok-europe.com/product/vk61-571h614' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'eligibleEnvironments', 'b5781120ccbc8985769d931d5d6c17ee6d65b33500903d8820d7f0520f8e0a65', (select id from public.sources where url = 'https://vostok-europe.com/product/vk61-571h614' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'ownershipFrictionLevels', 'e3c8833aa1e6b7e301cb9c74b3883b37ac16f6e3a73e83d8350c6b42f30775f3', (select id from public.sources where url = 'https://vostok-europe.com/product/vk61-571h614' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'traits', '4e2076a1c0b768078b77472745d76b5669626e4613ca5c72b718412d50253e80', (select id from public.sources where url = 'https://vostok-europe.com/product/vk61-571h614' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'identity', '13afc6f4332cd23783976ae8ce697afbc3b5713cca7328adc4a4cf616b7ec389', (select id from public.sources where url = 'https://www.vostok-europe.com/public/vendor/laravel-files/files/manuals-catalogues/ve-catalog-2024.pdf' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'movement', 'b051183eb452d792a8b72b7ad5b3129a79d20cb61b0f4b23cff5d3f10b233c96', (select id from public.sources where url = 'https://www.vostok-europe.com/public/vendor/laravel-files/files/manuals-catalogues/ve-catalog-2024.pdf' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'accuracy', 'ead46aa6762677bfc0e415efbf03f8523befaab03459a937ec4eb2ee97262a0f', (select id from public.sources where url = 'https://www.vostok-europe.com/public/vendor/laravel-files/files/manuals-catalogues/ve-catalog-2024.pdf' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'complications', 'e6b33e79c0e003ac264d4a6f7f310d08ded731d3c8a0c942db8288a6e8b50d87', (select id from public.sources where url = 'https://www.vostok-europe.com/public/vendor/laravel-files/files/manuals-catalogues/ve-catalog-2024.pdf' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'dateStatus', '94332144d941eb1212c9af7f968e215a7042bf94925c9c10b21de97a2f0cea06', (select id from public.sources where url = 'https://www.vostok-europe.com/public/vendor/laravel-files/files/manuals-catalogues/ve-catalog-2024.pdf' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'integratedBracelet', 'fcbcf165908dd18a9e49f7ff27810176db8e9f63b4352213741664245224f8aa', (select id from public.sources where url = 'https://vostok-europe.com/vendor/laravel-files/files/manuals-catalogues/new-2026/ve-users-guide-auto-en.pdf' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'attachmentType', 'd88fe7b6aa57e8f939fb2bdee085c5723652505bacd6ff99762e37989eec728b', (select id from public.sources where url = 'https://vostok-europe.com/vendor/laravel-files/files/manuals-catalogues/new-2026/ve-users-guide-auto-en.pdf' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'identity', '13afc6f4332cd23783976ae8ce697afbc3b5713cca7328adc4a4cf616b7ec389', (select id from public.sources where url = 'https://vostok-europe.com/archive' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'productionStatus', '4554955cd595aecef8df9d2837d1b53d5576a00b0d064c24281d37d9b18a4a02', (select id from public.sources where url = 'https://vostok-europe.com/archive' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'identity', '13afc6f4332cd23783976ae8ce697afbc3b5713cca7328adc4a4cf616b7ec389', (select id from public.sources where url = 'https://www.zlatnictvinoemi.cz/hodinky-vostok-europe-ssn571-nuclear-submarine-chrono-line-titanium-vk61-571h614-darek-zdarma' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'identity', '13afc6f4332cd23783976ae8ce697afbc3b5713cca7328adc4a4cf616b7ec389', (select id from public.sources where url = 'https://www.otto.de/p/vostok-europe-chronograph-nuclear-submarine-herrneuhr-vk61-571h614-lederband-46-mm-CS071P09T/' and retrieved_at = '2026-08-31T06:19:09Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-31T06:19:09Z'::timestamptz,
  '2026-08-31T06:19:09Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'materials', 'dfd018b406ec3af78de467f8460551487a5915fe3b9d166f3905b0bfcdbeda8f', (select id from public.sources where url = 'https://www.otto.de/p/vostok-europe-chronograph-nuclear-submarine-herrneuhr-vk61-571h614-lederband-46-mm-CS071P09T/' and retrieved_at = '2026-08-31T06:19:09Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-31T06:19:09Z'::timestamptz,
  '2026-08-31T06:19:09Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'weightFullG', '13671077b66a29874a2578b5240319092ef2a1043228e433e9b006b5e53e7513', (select id from public.sources where url = 'https://www.otto.de/p/vostok-europe-chronograph-nuclear-submarine-herrneuhr-vk61-571h614-lederband-46-mm-CS071P09T/' and retrieved_at = '2026-08-31T06:19:09Z'::timestamptz),
  '2026-08-30T19:32:02Z'::timestamptz, '2026-08-31T06:19:09Z'::timestamptz,
  '2026-08-31T06:19:09Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';



insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, stale_after, tier, reviewer
)
select 'price_snapshot', ps.id, 'amount_low_minor', '4f715c152c9ef539bf910918f6b6ec178bb27cda524bbf37f46873a3f9d254db', (select id from public.sources where url = 'https://www.zlatnictvinoemi.cz/hodinky-vostok-europe-ssn571-nuclear-submarine-chrono-line-titanium-vk61-571h614-darek-zdarma' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  ps.observed_at, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz,
  ps.stale_after, 'verified', 'catalogue-expansion-v1'
from public.price_snapshots ps
where ps.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614')
  and ps.kind = 'retail' and ps.condition = 'new'
  and ps.currency = 'EUR'
  and ps.observed_at = '2026-08-30T19:32:02Z'::timestamptz
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, stale_after = excluded.stale_after,
  tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, stale_after, tier, reviewer
)
select 'market_snapshot', ms.id, 'availability', '71c2950aec02c74e9101a11086d3ccfc7eceaf3d88393bc9debc4c4eecf8d337', (select id from public.sources where url = 'https://www.zlatnictvinoemi.cz/hodinky-vostok-europe-ssn571-nuclear-submarine-chrono-line-titanium-vk61-571h614-darek-zdarma' and retrieved_at = '2026-08-30T19:32:02Z'::timestamptz),
  ms.observed_at, '2026-08-30T19:32:02Z'::timestamptz,
  '2026-08-30T19:32:02Z'::timestamptz,
  ms.stale_after, 'verified', 'catalogue-expansion-v1'
from public.market_snapshots ms
where ms.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614')
  and ms.market_country_code = 'CZ'
  and ms.observed_at = '2026-08-30T19:32:02Z'::timestamptz
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, stale_after = excluded.stale_after,
  tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.completeness_evaluations (
  subject_type, subject_id, level, filter_contract_version, complete,
  completeness_score, missing_fields, evaluated_at
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'm0', 1,
  true, 1.0000, array[]::text[],
  '2026-08-30T19:32:02Z'::timestamptz
)
on conflict (subject_type, subject_id, level, filter_contract_version) do update set
  complete = excluded.complete,
  completeness_score = excluded.completeness_score,
  missing_fields = excluded.missing_fields,
  evaluated_at = excluded.evaluated_at;

insert into public.completeness_evaluations (
  subject_type, subject_id, level, filter_contract_version, complete,
  completeness_score, missing_fields, evaluated_at
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'm1', 1,
  true, 1.0000, array[]::text[],
  '2026-08-30T19:32:02Z'::timestamptz
)
on conflict (subject_type, subject_id, level, filter_contract_version) do update set
  complete = excluded.complete,
  completeness_score = excluded.completeness_score,
  missing_fields = excluded.missing_fields,
  evaluated_at = excluded.evaluated_at;

insert into public.completeness_evaluations (
  subject_type, subject_id, level, filter_contract_version, complete,
  completeness_score, missing_fields, evaluated_at
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok-europe' and rv.variant_key = 'vostok-europe-vk61-571h614'), 'm2', 1,
  false, 0.6667, array['market']::text[],
  '2026-08-30T19:32:02Z'::timestamptz
)
on conflict (subject_type, subject_id, level, filter_contract_version) do update set
  complete = excluded.complete,
  completeness_score = excluded.completeness_score,
  missing_fields = excluded.missing_fields,
  evaluated_at = excluded.evaluated_at;
