-- Generated by scripts/render-seed-migration.ts from the reviewed seed bundle.
-- Additive expansion for: vostok-amphibia-420059.

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.vostokinc.ru/catalog/amfibiya_muzhskaya/15/amfibiya_420059/', 'https://www.vostokinc.ru/catalog/amfibiya_muzhskaya/15/amfibiya_420059/', 'Amphibia 420059 — 2416/420059', 'Chistopol Watch Factory Vostok', 'manufacturer_product', '2026-08-30T18:40:51Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://online.vostokinc.ru/katalog-tovarov/amfibiya-420059', 'https://online.vostokinc.ru/katalog-tovarov/amfibiya-420059', 'Amphibia 420059 factory shop', 'Chistopol Watch Factory Vostok', 'manufacturer_product', '2026-08-30T18:40:51Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://meranom.com/en/amphibian-classic/420/vostok-watch-amphibian-classic-420059.html', 'https://meranom.com/en/amphibian-classic/420/vostok-watch-amphibian-classic-420059.html', 'Vostok Amphibian Classic 420059', 'Meranom', 'secondary_editorial', '2026-08-30T18:40:51Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://meranom.com/en/about_meranom.html', 'https://meranom.com/en/about_meranom.html', 'About Meranom and factory relationships', 'Meranom', 'secondary_editorial', '2026-08-30T18:40:51Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.bestwatch.ru/watch/Vostok/2416.00-420059/', 'https://www.bestwatch.ru/watch/Vostok/2416.00-420059/', 'Vostok 2416.00-420059 exact-reference listing', 'Bestwatch.ru', 'secondary_editorial', '2026-08-30T18:40:51Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://scubadudestore.com/products/vostok-amphibia-420059', 'https://scubadudestore.com/products/vostok-amphibia-420059', 'Vostok Amphibia 420059', 'Scuba Dude Store', 'secondary_editorial', '2026-08-30T18:40:51Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.thewatchcompany.com/blog/recommended/vostok-amphibian-scuba-dude-review/', 'https://www.thewatchcompany.com/blog/recommended/vostok-amphibian-scuba-dude-review/', 'Vostok Amphibian Scuba Dude review', 'The Watch Company', 'secondary_editorial', '2026-08-30T18:40:51Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://ticknsip.blogspot.com/2021/09/vostok-amphibia-scuba-dude-review.html', 'https://ticknsip.blogspot.com/2021/09/vostok-amphibia-scuba-dude-review.html', 'Vostok Amphibia Scuba Dude review', 'Tick & Sip', 'secondary_editorial', '2026-08-30T18:40:51Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.ebay.co.uk/urw/Vostok-Amphibia-Stainless-Steel-Russian-Military-Diver-Watch-420059/product-reviews/19034189571', 'https://www.ebay.co.uk/urw/Vostok-Amphibia-Stainless-Steel-Russian-Military-Diver-Watch-420059/product-reviews/19034189571', 'Vostok 420059 verified-purchase reviews', 'eBay', 'secondary_editorial', '2026-08-30T18:40:51Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.reddit.com/r/Watches/comments/sbqkkt', 'https://www.reddit.com/r/Watches/comments/sbqkkt', 'Vostok 420059 long-term owner report', 'Reddit', 'secondary_editorial', '2026-08-30T18:40:51Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.reddit.com/r/Watchexchange/comments/1kspylc', 'https://www.reddit.com/r/Watchexchange/comments/1kspylc', 'Vostok Amphibia 420059 original bracelet listing', 'Reddit', 'secondary_editorial', '2026-08-31T08:47:55Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://vostok-world24.com/en/products/vostok-federstege-edelstahl-fur-russische-uhren', 'https://vostok-world24.com/en/products/vostok-federstege-edelstahl-fur-russische-uhren', 'Vostok stainless steel spring bars for Russian watches', 'Vostok-World24', 'secondary_editorial', '2026-08-31T08:47:55Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.brands (slug, name, review_status)
values ('vostok', 'Vostok', 'accepted')
on conflict (slug) do update set name = excluded.name, review_status = 'accepted', updated_at = now();

insert into public.collections (brand_id, slug, name, review_status)
select id, 'amphibia-classic', 'Amphibia Classic', 'accepted'
from public.brands where slug = 'vostok'
on conflict (brand_id, slug) do update set name = excluded.name, review_status = 'accepted', updated_at = now();

insert into public.reference_models (collection_id, slug, model_name, review_status)
select c.id, 'amphibia', 'Amphibia', 'accepted'
from public.collections c join public.brands b on b.id = c.brand_id
where b.slug = 'vostok' and c.slug = 'amphibia-classic'
on conflict (collection_id, slug) do update set model_name = excluded.model_name, review_status = 'accepted', updated_at = now();

insert into public.reference_variants (
  reference_model_id, variant_key, reference_code, variant_name,
  case_material, caseback_material, bracelet_material, strap_material,
  nickel_contact_risk, case_diameter_mm, case_width_mm, case_length_mm,
  case_thickness_mm, lug_to_lug_mm,
  lug_to_lug_measured, lug_width_mm, lug_curvature, integrated_bracelet,
  weight_full_g, movement_type, caliber_ref, power_reserve_h,
  accuracy_lower_seconds, accuracy_upper_seconds, accuracy_period_days,
  water_resistance_m, crown_type, crown_position, crystal, lume_grade,
  bracelet_attachment, shock_resistant, production_status, review_status
)
values (
  (select rm.id from public.reference_models rm join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and c.slug = 'amphibia-classic' and rm.slug = 'amphibia'), 'vostok-amphibia-420059', '420059', 'Scuba Dude blue dial on supplied stainless-steel bracelet',
  'stainless steel', null, 'stainless steel', null,
  null, 39.6, null, null,
  15, 46,
  false, 18, null, false,
  128, 'automatic', 'Vostok 2416B', 31,
  -20, 60, 1,
  200, 'screw_down', null, 'acrylic', 'weak',
  'spring_bar', null, 'current', 'accepted'
)
on conflict (reference_model_id, variant_key) do update set
  reference_code = excluded.reference_code,
  variant_name = excluded.variant_name,
  case_material = excluded.case_material,
  caseback_material = excluded.caseback_material,
  bracelet_material = excluded.bracelet_material,
  strap_material = excluded.strap_material,
  nickel_contact_risk = excluded.nickel_contact_risk,
  case_diameter_mm = excluded.case_diameter_mm,
  case_width_mm = excluded.case_width_mm,
  case_length_mm = excluded.case_length_mm,
  case_thickness_mm = excluded.case_thickness_mm,
  lug_to_lug_mm = excluded.lug_to_lug_mm,
  lug_to_lug_measured = excluded.lug_to_lug_measured,
  lug_width_mm = excluded.lug_width_mm,
  lug_curvature = excluded.lug_curvature,
  integrated_bracelet = excluded.integrated_bracelet,
  weight_full_g = excluded.weight_full_g,
  movement_type = excluded.movement_type,
  caliber_ref = excluded.caliber_ref,
  power_reserve_h = excluded.power_reserve_h,
  accuracy_lower_seconds = excluded.accuracy_lower_seconds,
  accuracy_upper_seconds = excluded.accuracy_upper_seconds,
  accuracy_period_days = excluded.accuracy_period_days,
  water_resistance_m = excluded.water_resistance_m,
  crown_type = excluded.crown_type,
  crown_position = excluded.crown_position,
  crystal = excluded.crystal,
  lume_grade = excluded.lume_grade,
  bracelet_attachment = excluded.bracelet_attachment,
  shock_resistant = excluded.shock_resistant,
  production_status = excluded.production_status,
  review_status = 'accepted',
  updated_at = now();

update public.reference_variants
set product_url = 'https://www.vostokinc.ru/catalog/amfibiya_muzhskaya/15/amfibiya_420059/', updated_at = now()
where id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059')
  and product_url is distinct from 'https://www.vostokinc.ru/catalog/amfibiya_muzhskaya/15/amfibiya_420059/';

insert into public.reference_complications (reference_variant_id, complication)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'date')
on conflict (reference_variant_id, complication) do nothing;

insert into public.price_snapshots (
  reference_variant_id, kind, condition, currency, amount_low_minor,
  market_country_code, observed_at, stale_after, review_status
)
select (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'retail', 'new', 'USD', 16400,
  'RU', '2026-08-30T18:40:51Z'::timestamptz, '2027-02-26T18:40:51Z'::timestamptz, 'accepted'
where not exists (
  select 1 from public.price_snapshots ps
  where ps.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059')
    and ps.kind = 'retail' and ps.condition = 'new'
    and ps.currency = 'USD'
    and ps.observed_at = '2026-08-30T18:40:51Z'::timestamptz
);

insert into public.market_snapshots (
  reference_variant_id, market_country_code, availability, observed_at,
  stale_after, review_status
)
  select (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'RU', 'in_stock',
  '2026-08-30T18:40:51Z'::timestamptz,
  '2026-09-29T18:40:51Z'::timestamptz, 'accepted'
where not exists (
  select 1 from public.market_snapshots ms
  where ms.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059')
    and ms.market_country_code = 'RU'
    and ms.observed_at = '2026-08-30T18:40:51Z'::timestamptz
);

insert into public.reference_deployment_profiles (
  reference_variant_id, environment, review_status
)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'field_water_abuse', 'accepted')
on conflict (reference_variant_id, environment) do update set
  review_status = 'accepted';

insert into public.reference_ownership_friction_profiles (
  reference_variant_id, friction_level, review_status
)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'workhorse_mechanical', 'accepted')
on conflict (reference_variant_id, friction_level) do update set
  review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'primary_archetype', 'accessible_dive_mechanical', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'social_signal', 'anti_luxury', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'aesthetic_dna', 'structural_tool', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'emotional_objective', 'dependability', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'emotional_objective', 'differentiation', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'identity', 'a96d24dd7825e91ddea350b08df93d965f5b74a0ff89a62bb2c50efc4d3abfa7', (select id from public.sources where url = 'https://www.vostokinc.ru/catalog/amfibiya_muzhskaya/15/amfibiya_420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'materials', '2aa17ffae5c2a2207b6d3ae94a6567472d014999d585ab9b441b514e11505428', (select id from public.sources where url = 'https://www.vostokinc.ru/catalog/amfibiya_muzhskaya/15/amfibiya_420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'productionStatus', '694df57a7909d9f9edbd3acb4ccfce5fbee156fab749383121f17fef16bbab57', (select id from public.sources where url = 'https://www.vostokinc.ru/catalog/amfibiya_muzhskaya/15/amfibiya_420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'caseDiameterMm', '34b83a967c732f0184a11fc9cb4fa3714fab96a618837bb6557b38c520c668c4', (select id from public.sources where url = 'https://www.vostokinc.ru/catalog/amfibiya_muzhskaya/15/amfibiya_420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'caseThicknessMm', 'e629fa6598d732768f7c726b4b621285f9c3b85303900aa912017db7617d8bdb', (select id from public.sources where url = 'https://www.vostokinc.ru/catalog/amfibiya_muzhskaya/15/amfibiya_420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'lugToLugMm', '25fc0e7096fc653718202dc30b0c580b8ab87eac11a700cba03a7c021bc35b0c', (select id from public.sources where url = 'https://www.vostokinc.ru/catalog/amfibiya_muzhskaya/15/amfibiya_420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'lugWidthMm', '4ec9599fc203d176a301536c2e091a19bc852759b255bd6818810a42c5fed14a', (select id from public.sources where url = 'https://www.vostokinc.ru/catalog/amfibiya_muzhskaya/15/amfibiya_420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'weightFullG', '2747b7c718564ba5f066f0523b03e17f6a496b06851333d2d59ab6d863225848', (select id from public.sources where url = 'https://www.vostokinc.ru/catalog/amfibiya_muzhskaya/15/amfibiya_420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'movement', '3b9e446f7aa7f202ab065e76b46fc88bfab9e56b59127c7707dc1bd4cc441963', (select id from public.sources where url = 'https://www.vostokinc.ru/catalog/amfibiya_muzhskaya/15/amfibiya_420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'accuracy', '331985a27520d5d430daa06d75727af98908ef19c5c723d7e5ebaf1c8456431d', (select id from public.sources where url = 'https://www.vostokinc.ru/catalog/amfibiya_muzhskaya/15/amfibiya_420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'waterResistanceM', '27badc983df1780b60c2b3fa9d3a19a00e46aac798451f0febdca52920faaddf', (select id from public.sources where url = 'https://www.vostokinc.ru/catalog/amfibiya_muzhskaya/15/amfibiya_420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'crownType', '2026fa400c91bf0e5fd82a1b3b951961bbb0fd2f862c4142a26aa6d59e82ce34', (select id from public.sources where url = 'https://www.vostokinc.ru/catalog/amfibiya_muzhskaya/15/amfibiya_420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'crystal', 'a9399b78a2e24dcfef093fd8e9f681cf02110cae5d1a52bdcb4ecceee5be88a3', (select id from public.sources where url = 'https://www.vostokinc.ru/catalog/amfibiya_muzhskaya/15/amfibiya_420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'integratedBracelet', 'fcbcf165908dd18a9e49f7ff27810176db8e9f63b4352213741664245224f8aa', (select id from public.sources where url = 'https://www.vostokinc.ru/catalog/amfibiya_muzhskaya/15/amfibiya_420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'dateStatus', '94332144d941eb1212c9af7f968e215a7042bf94925c9c10b21de97a2f0cea06', (select id from public.sources where url = 'https://www.vostokinc.ru/catalog/amfibiya_muzhskaya/15/amfibiya_420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'eligibleEnvironments', '7081e94de70b2f62f36ef290dfc10647593c1e0d8e98bc076d357adbc5b27491', (select id from public.sources where url = 'https://www.vostokinc.ru/catalog/amfibiya_muzhskaya/15/amfibiya_420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'ownershipFrictionLevels', '582066aec46a0e953a89b01aca2612ef776f66237e411fec8fb5f77652aaee62', (select id from public.sources where url = 'https://www.vostokinc.ru/catalog/amfibiya_muzhskaya/15/amfibiya_420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'traits', '3671751ef9d194427d883c13583a889c9b6eb7b28542cc7e54f8f45aa0107758', (select id from public.sources where url = 'https://www.vostokinc.ru/catalog/amfibiya_muzhskaya/15/amfibiya_420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'identity', 'a96d24dd7825e91ddea350b08df93d965f5b74a0ff89a62bb2c50efc4d3abfa7', (select id from public.sources where url = 'https://online.vostokinc.ru/katalog-tovarov/amfibiya-420059' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'materials', '2aa17ffae5c2a2207b6d3ae94a6567472d014999d585ab9b441b514e11505428', (select id from public.sources where url = 'https://online.vostokinc.ru/katalog-tovarov/amfibiya-420059' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'productionStatus', '694df57a7909d9f9edbd3acb4ccfce5fbee156fab749383121f17fef16bbab57', (select id from public.sources where url = 'https://online.vostokinc.ru/katalog-tovarov/amfibiya-420059' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'identity', 'a96d24dd7825e91ddea350b08df93d965f5b74a0ff89a62bb2c50efc4d3abfa7', (select id from public.sources where url = 'https://meranom.com/en/amphibian-classic/420/vostok-watch-amphibian-classic-420059.html' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'materials', '2aa17ffae5c2a2207b6d3ae94a6567472d014999d585ab9b441b514e11505428', (select id from public.sources where url = 'https://meranom.com/en/amphibian-classic/420/vostok-watch-amphibian-classic-420059.html' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'movement', '3b9e446f7aa7f202ab065e76b46fc88bfab9e56b59127c7707dc1bd4cc441963', (select id from public.sources where url = 'https://meranom.com/en/amphibian-classic/420/vostok-watch-amphibian-classic-420059.html' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'accuracy', '331985a27520d5d430daa06d75727af98908ef19c5c723d7e5ebaf1c8456431d', (select id from public.sources where url = 'https://meranom.com/en/amphibian-classic/420/vostok-watch-amphibian-classic-420059.html' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'waterResistanceM', '27badc983df1780b60c2b3fa9d3a19a00e46aac798451f0febdca52920faaddf', (select id from public.sources where url = 'https://meranom.com/en/amphibian-classic/420/vostok-watch-amphibian-classic-420059.html' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'crownType', '2026fa400c91bf0e5fd82a1b3b951961bbb0fd2f862c4142a26aa6d59e82ce34', (select id from public.sources where url = 'https://meranom.com/en/amphibian-classic/420/vostok-watch-amphibian-classic-420059.html' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'crystal', 'a9399b78a2e24dcfef093fd8e9f681cf02110cae5d1a52bdcb4ecceee5be88a3', (select id from public.sources where url = 'https://meranom.com/en/amphibian-classic/420/vostok-watch-amphibian-classic-420059.html' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'dateStatus', '94332144d941eb1212c9af7f968e215a7042bf94925c9c10b21de97a2f0cea06', (select id from public.sources where url = 'https://meranom.com/en/amphibian-classic/420/vostok-watch-amphibian-classic-420059.html' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'identity', 'a96d24dd7825e91ddea350b08df93d965f5b74a0ff89a62bb2c50efc4d3abfa7', (select id from public.sources where url = 'https://www.bestwatch.ru/watch/Vostok/2416.00-420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'caseDiameterMm', '34b83a967c732f0184a11fc9cb4fa3714fab96a618837bb6557b38c520c668c4', (select id from public.sources where url = 'https://www.bestwatch.ru/watch/Vostok/2416.00-420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'caseThicknessMm', 'e629fa6598d732768f7c726b4b621285f9c3b85303900aa912017db7617d8bdb', (select id from public.sources where url = 'https://www.bestwatch.ru/watch/Vostok/2416.00-420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'lugToLugMm', '25fc0e7096fc653718202dc30b0c580b8ab87eac11a700cba03a7c021bc35b0c', (select id from public.sources where url = 'https://www.bestwatch.ru/watch/Vostok/2416.00-420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'lugWidthMm', '4ec9599fc203d176a301536c2e091a19bc852759b255bd6818810a42c5fed14a', (select id from public.sources where url = 'https://www.bestwatch.ru/watch/Vostok/2416.00-420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'weightFullG', '2747b7c718564ba5f066f0523b03e17f6a496b06851333d2d59ab6d863225848', (select id from public.sources where url = 'https://www.bestwatch.ru/watch/Vostok/2416.00-420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'movement', '3b9e446f7aa7f202ab065e76b46fc88bfab9e56b59127c7707dc1bd4cc441963', (select id from public.sources where url = 'https://www.bestwatch.ru/watch/Vostok/2416.00-420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'accuracy', '331985a27520d5d430daa06d75727af98908ef19c5c723d7e5ebaf1c8456431d', (select id from public.sources where url = 'https://www.bestwatch.ru/watch/Vostok/2416.00-420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'waterResistanceM', '27badc983df1780b60c2b3fa9d3a19a00e46aac798451f0febdca52920faaddf', (select id from public.sources where url = 'https://www.bestwatch.ru/watch/Vostok/2416.00-420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'crystal', 'a9399b78a2e24dcfef093fd8e9f681cf02110cae5d1a52bdcb4ecceee5be88a3', (select id from public.sources where url = 'https://www.bestwatch.ru/watch/Vostok/2416.00-420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'lumeGrade', '06ee15d2756a4d073ada12f2dae65756a19e749eee7247b0bc321b3d307f6b52', (select id from public.sources where url = 'https://www.bestwatch.ru/watch/Vostok/2416.00-420059/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'identity', 'a96d24dd7825e91ddea350b08df93d965f5b74a0ff89a62bb2c50efc4d3abfa7', (select id from public.sources where url = 'https://scubadudestore.com/products/vostok-amphibia-420059' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'weightFullG', '2747b7c718564ba5f066f0523b03e17f6a496b06851333d2d59ab6d863225848', (select id from public.sources where url = 'https://scubadudestore.com/products/vostok-amphibia-420059' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'identity', 'a96d24dd7825e91ddea350b08df93d965f5b74a0ff89a62bb2c50efc4d3abfa7', (select id from public.sources where url = 'https://www.thewatchcompany.com/blog/recommended/vostok-amphibian-scuba-dude-review/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'lumeGrade', '06ee15d2756a4d073ada12f2dae65756a19e749eee7247b0bc321b3d307f6b52', (select id from public.sources where url = 'https://www.thewatchcompany.com/blog/recommended/vostok-amphibian-scuba-dude-review/' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'identity', 'a96d24dd7825e91ddea350b08df93d965f5b74a0ff89a62bb2c50efc4d3abfa7', (select id from public.sources where url = 'https://ticknsip.blogspot.com/2021/09/vostok-amphibia-scuba-dude-review.html' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'lumeGrade', '06ee15d2756a4d073ada12f2dae65756a19e749eee7247b0bc321b3d307f6b52', (select id from public.sources where url = 'https://ticknsip.blogspot.com/2021/09/vostok-amphibia-scuba-dude-review.html' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'identity', 'a96d24dd7825e91ddea350b08df93d965f5b74a0ff89a62bb2c50efc4d3abfa7', (select id from public.sources where url = 'https://www.ebay.co.uk/urw/Vostok-Amphibia-Stainless-Steel-Russian-Military-Diver-Watch-420059/product-reviews/19034189571' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'lumeGrade', '06ee15d2756a4d073ada12f2dae65756a19e749eee7247b0bc321b3d307f6b52', (select id from public.sources where url = 'https://www.ebay.co.uk/urw/Vostok-Amphibia-Stainless-Steel-Russian-Military-Diver-Watch-420059/product-reviews/19034189571' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'identity', 'a96d24dd7825e91ddea350b08df93d965f5b74a0ff89a62bb2c50efc4d3abfa7', (select id from public.sources where url = 'https://www.reddit.com/r/Watches/comments/sbqkkt' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'lumeGrade', '06ee15d2756a4d073ada12f2dae65756a19e749eee7247b0bc321b3d307f6b52', (select id from public.sources where url = 'https://www.reddit.com/r/Watches/comments/sbqkkt' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'identity', 'a96d24dd7825e91ddea350b08df93d965f5b74a0ff89a62bb2c50efc4d3abfa7', (select id from public.sources where url = 'https://www.reddit.com/r/Watchexchange/comments/1kspylc' and retrieved_at = '2026-08-31T08:47:55Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-31T08:47:55Z'::timestamptz,
  '2026-08-31T08:47:55Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'attachmentType', 'dc8f261bad159c55d8fb5a6cdf75774951c242716e8306aaaad0e1a7b999db27', (select id from public.sources where url = 'https://www.reddit.com/r/Watchexchange/comments/1kspylc' and retrieved_at = '2026-08-31T08:47:55Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-31T08:47:55Z'::timestamptz,
  '2026-08-31T08:47:55Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'attachmentType', 'dc8f261bad159c55d8fb5a6cdf75774951c242716e8306aaaad0e1a7b999db27', (select id from public.sources where url = 'https://vostok-world24.com/en/products/vostok-federstege-edelstahl-fur-russische-uhren' and retrieved_at = '2026-08-31T08:47:55Z'::timestamptz),
  '2026-08-30T18:40:51Z'::timestamptz, '2026-08-31T08:47:55Z'::timestamptz,
  '2026-08-31T08:47:55Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';



insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, stale_after, tier, reviewer
)
select 'price_snapshot', ps.id, 'amount_low_minor', '2ab0e1123d397a58f7a839d63ff07e99ca4e386f3eb93e4ae4316d2e9cbf27ff', (select id from public.sources where url = 'https://meranom.com/en/amphibian-classic/420/vostok-watch-amphibian-classic-420059.html' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  ps.observed_at, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz,
  ps.stale_after, 'verified', 'catalogue-expansion-v1'
from public.price_snapshots ps
where ps.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059')
  and ps.kind = 'retail' and ps.condition = 'new'
  and ps.currency = 'USD'
  and ps.observed_at = '2026-08-30T18:40:51Z'::timestamptz
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, stale_after = excluded.stale_after,
  tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, stale_after, tier, reviewer
)
select 'price_snapshot', ps.id, 'amount_low_minor', '2ab0e1123d397a58f7a839d63ff07e99ca4e386f3eb93e4ae4316d2e9cbf27ff', (select id from public.sources where url = 'https://meranom.com/en/about_meranom.html' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  ps.observed_at, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz,
  ps.stale_after, 'verified', 'catalogue-expansion-v1'
from public.price_snapshots ps
where ps.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059')
  and ps.kind = 'retail' and ps.condition = 'new'
  and ps.currency = 'USD'
  and ps.observed_at = '2026-08-30T18:40:51Z'::timestamptz
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, stale_after = excluded.stale_after,
  tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, stale_after, tier, reviewer
)
select 'market_snapshot', ms.id, 'availability', 'a0d00556b975b95064b17e1539e14b4d7097a8121a370eab0bac44fe1eea8a10', (select id from public.sources where url = 'https://meranom.com/en/amphibian-classic/420/vostok-watch-amphibian-classic-420059.html' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  ms.observed_at, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz,
  ms.stale_after, 'verified', 'catalogue-expansion-v1'
from public.market_snapshots ms
where ms.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059')
  and ms.market_country_code = 'RU'
  and ms.observed_at = '2026-08-30T18:40:51Z'::timestamptz
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, stale_after = excluded.stale_after,
  tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, stale_after, tier, reviewer
)
select 'market_snapshot', ms.id, 'availability', 'a0d00556b975b95064b17e1539e14b4d7097a8121a370eab0bac44fe1eea8a10', (select id from public.sources where url = 'https://meranom.com/en/about_meranom.html' and retrieved_at = '2026-08-30T18:40:51Z'::timestamptz),
  ms.observed_at, '2026-08-30T18:40:51Z'::timestamptz,
  '2026-08-30T18:40:51Z'::timestamptz,
  ms.stale_after, 'verified', 'catalogue-expansion-v1'
from public.market_snapshots ms
where ms.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059')
  and ms.market_country_code = 'RU'
  and ms.observed_at = '2026-08-30T18:40:51Z'::timestamptz
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, stale_after = excluded.stale_after,
  tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.completeness_evaluations (
  subject_type, subject_id, level, filter_contract_version, complete,
  completeness_score, missing_fields, evaluated_at
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'm0', 1,
  true, 1.0000, array[]::text[],
  '2026-08-30T18:40:51Z'::timestamptz
)
on conflict (subject_type, subject_id, level, filter_contract_version) do update set
  complete = excluded.complete,
  completeness_score = excluded.completeness_score,
  missing_fields = excluded.missing_fields,
  evaluated_at = excluded.evaluated_at;

insert into public.completeness_evaluations (
  subject_type, subject_id, level, filter_contract_version, complete,
  completeness_score, missing_fields, evaluated_at
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'm1', 1,
  true, 1.0000, array[]::text[],
  '2026-08-30T18:40:51Z'::timestamptz
)
on conflict (subject_type, subject_id, level, filter_contract_version) do update set
  complete = excluded.complete,
  completeness_score = excluded.completeness_score,
  missing_fields = excluded.missing_fields,
  evaluated_at = excluded.evaluated_at;

insert into public.completeness_evaluations (
  subject_type, subject_id, level, filter_contract_version, complete,
  completeness_score, missing_fields, evaluated_at
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'vostok' and rv.variant_key = 'vostok-amphibia-420059'), 'm2', 1,
  false, 0.6667, array['market']::text[],
  '2026-08-30T18:40:51Z'::timestamptz
)
on conflict (subject_type, subject_id, level, filter_contract_version) do update set
  complete = excluded.complete,
  completeness_score = excluded.completeness_score,
  missing_fields = excluded.missing_fields,
  evaluated_at = excluded.evaluated_at;
