-- Generated by scripts/render-seed-migration.ts from the reviewed seed bundle.
-- Additive expansion for: boldr-odyssey-horizon-druber-gmt.

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://wornandwound.com/review/hands-on-the-new-boldr-odyssey/', 'https://wornandwound.com/review/hands-on-the-new-boldr-odyssey/', 'Hands-On: the New BOLDR Odyssey Horizon', 'Worn & Wound', 'secondary_editorial', '2026-08-31T09:30:00Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.boldrsupply.co/products/odyssey-horizon?country=US', 'https://www.boldrsupply.co/products/odyssey-horizon?country=US', 'Odyssey Horizon — ODY-TI-40-H-BL', 'BOLDR Supply Co.', 'manufacturer_product', '2026-08-30T19:50:24Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.boldrsupply.co/blogs/press-releases/dive-boldly-live-colorfully-the-odyssey-reimagined', 'https://www.boldrsupply.co/blogs/press-releases/dive-boldly-live-colorfully-the-odyssey-reimagined', 'Dive Boldly, Live Colorfully: The Odyssey Reimagined', 'BOLDR Supply Co.', 'manufacturer_product', '2026-08-30T19:50:24Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://miyotamovement.com/product/9075/', 'https://miyotamovement.com/product/9075/', 'Miyota calibre 9075 specification', 'Citizen Watch Co. / Miyota', 'manufacturer_data_sheet', '2026-08-30T19:50:24Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.brands (slug, name, review_status)
values ('boldr', 'BOLDR Supply Co.', 'accepted')
on conflict (slug) do update set name = excluded.name, review_status = 'accepted', updated_at = now();

insert into public.collections (brand_id, slug, name, review_status)
select id, 'odyssey', 'Odyssey', 'accepted'
from public.brands where slug = 'boldr'
on conflict (brand_id, slug) do update set name = excluded.name, review_status = 'accepted', updated_at = now();

insert into public.reference_models (collection_id, slug, model_name, review_status)
select c.id, 'odyssey-horizon', 'Odyssey Horizon', 'accepted'
from public.collections c join public.brands b on b.id = c.brand_id
where b.slug = 'boldr' and c.slug = 'odyssey'
on conflict (collection_id, slug) do update set model_name = excluded.model_name, review_status = 'accepted', updated_at = now();

insert into public.reference_variants (
  reference_model_id, variant_key, reference_code, variant_name,
  case_material, caseback_material, bracelet_material, strap_material,
  nickel_contact_risk, case_diameter_mm, case_width_mm, case_length_mm,
  case_thickness_mm, lug_to_lug_mm,
  lug_to_lug_measured, lug_width_mm, lug_curvature, integrated_bracelet,
  weight_full_g, movement_type, caliber_ref, power_reserve_h,
  accuracy_lower_seconds, accuracy_upper_seconds, accuracy_period_days,
  water_resistance_m, crown_type, crown_position, crystal, lume_grade,
  bracelet_attachment, shock_resistant, production_status, review_status
)
values (
  (select rm.id from public.reference_models rm join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and c.slug = 'odyssey' and rm.slug = 'odyssey-horizon'), 'boldr-odyssey-horizon-druber-gmt', 'ODY-TI-40-H-BL', 'Horizon on integrated Druber strap; titanium bracelet included',
  'titanium', 'titanium with sapphire exhibition caseback', null, 'integrated Druber rubber',
  null, 40, null, null,
  13, 48,
  false, 20, null, false,
  91, 'automatic', 'Miyota 9075', 42,
  -10, 30, 1,
  300, 'screw_down', null, 'sapphire', 'strong',
  'integrated', null, 'current', 'accepted'
)
on conflict (reference_model_id, variant_key) do update set
  reference_code = excluded.reference_code,
  variant_name = excluded.variant_name,
  case_material = excluded.case_material,
  caseback_material = excluded.caseback_material,
  bracelet_material = excluded.bracelet_material,
  strap_material = excluded.strap_material,
  nickel_contact_risk = excluded.nickel_contact_risk,
  case_diameter_mm = excluded.case_diameter_mm,
  case_width_mm = excluded.case_width_mm,
  case_length_mm = excluded.case_length_mm,
  case_thickness_mm = excluded.case_thickness_mm,
  lug_to_lug_mm = excluded.lug_to_lug_mm,
  lug_to_lug_measured = excluded.lug_to_lug_measured,
  lug_width_mm = excluded.lug_width_mm,
  lug_curvature = excluded.lug_curvature,
  integrated_bracelet = excluded.integrated_bracelet,
  weight_full_g = excluded.weight_full_g,
  movement_type = excluded.movement_type,
  caliber_ref = excluded.caliber_ref,
  power_reserve_h = excluded.power_reserve_h,
  accuracy_lower_seconds = excluded.accuracy_lower_seconds,
  accuracy_upper_seconds = excluded.accuracy_upper_seconds,
  accuracy_period_days = excluded.accuracy_period_days,
  water_resistance_m = excluded.water_resistance_m,
  crown_type = excluded.crown_type,
  crown_position = excluded.crown_position,
  crystal = excluded.crystal,
  lume_grade = excluded.lume_grade,
  bracelet_attachment = excluded.bracelet_attachment,
  shock_resistant = excluded.shock_resistant,
  production_status = excluded.production_status,
  review_status = 'accepted',
  updated_at = now();

update public.reference_variants
set product_url = 'https://www.boldrsupply.co/products/odyssey-horizon?country=US', updated_at = now()
where id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt')
  and product_url is distinct from 'https://www.boldrsupply.co/products/odyssey-horizon?country=US';

insert into public.reference_complications (reference_variant_id, complication)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'gmt')
on conflict (reference_variant_id, complication) do nothing;

insert into public.reference_complications (reference_variant_id, complication)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'date')
on conflict (reference_variant_id, complication) do nothing;

insert into public.price_snapshots (
  reference_variant_id, kind, condition, currency, amount_low_minor,
  market_country_code, observed_at, stale_after, review_status
)
select (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'retail', 'new', 'USD', 79900,
  'US', '2026-08-31T09:30:00Z'::timestamptz, '2027-02-27T09:30:00Z'::timestamptz, 'accepted'
where not exists (
  select 1 from public.price_snapshots ps
  where ps.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt')
    and ps.kind = 'retail' and ps.condition = 'new'
    and ps.currency = 'USD'
    and ps.observed_at = '2026-08-31T09:30:00Z'::timestamptz
);

insert into public.market_snapshots (
  reference_variant_id, market_country_code, availability, observed_at,
  stale_after, review_status
)
  select (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'US', 'in_stock',
  '2026-08-31T09:30:00Z'::timestamptz,
  '2026-09-30T09:30:00Z'::timestamptz, 'accepted'
where not exists (
  select 1 from public.market_snapshots ms
  where ms.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt')
    and ms.market_country_code = 'US'
    and ms.observed_at = '2026-08-31T09:30:00Z'::timestamptz
);

insert into public.reference_deployment_profiles (
  reference_variant_id, environment, review_status
)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'field_water_abuse', 'accepted')
on conflict (reference_variant_id, environment) do update set
  review_status = 'accepted';

insert into public.reference_deployment_profiles (
  reference_variant_id, environment, review_status
)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'studio_desk_daily', 'accepted')
on conflict (reference_variant_id, environment) do update set
  review_status = 'accepted';

insert into public.reference_ownership_friction_profiles (
  reference_variant_id, friction_level, review_status
)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'workhorse_mechanical', 'accepted')
on conflict (reference_variant_id, friction_level) do update set
  review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'primary_archetype', 'compact_independent_travel_tool', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'social_signal', 'unapologetic_benchmark', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'aesthetic_dna', 'structural_tool', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'emotional_objective', 'dependability', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'emotional_objective', 'differentiation', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'identity', '253f4ebdb0bda0cdae7779ef0e3803109f5754d71962a0ceb8dde5be9117d85c', (select id from public.sources where url = 'https://www.boldrsupply.co/products/odyssey-horizon?country=US' and retrieved_at = '2026-08-30T19:50:24Z'::timestamptz),
  '2026-08-31T09:30:00Z'::timestamptz, '2026-08-30T19:50:24Z'::timestamptz,
  '2026-08-30T19:50:24Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'materials', 'defe5757ef5dfd67fae9db51c6159d207cdbb7ee46ae4742dffb72be14d7ec2f', (select id from public.sources where url = 'https://www.boldrsupply.co/products/odyssey-horizon?country=US' and retrieved_at = '2026-08-30T19:50:24Z'::timestamptz),
  '2026-08-31T09:30:00Z'::timestamptz, '2026-08-30T19:50:24Z'::timestamptz,
  '2026-08-30T19:50:24Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'productionStatus', '694df57a7909d9f9edbd3acb4ccfce5fbee156fab749383121f17fef16bbab57', (select id from public.sources where url = 'https://www.boldrsupply.co/products/odyssey-horizon?country=US' and retrieved_at = '2026-08-30T19:50:24Z'::timestamptz),
  '2026-08-31T09:30:00Z'::timestamptz, '2026-08-30T19:50:24Z'::timestamptz,
  '2026-08-30T19:50:24Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'caseDiameterMm', 'd59eced1ded07f84c145592f65bdf854358e009c5cd705f5215bf18697fed103', (select id from public.sources where url = 'https://www.boldrsupply.co/products/odyssey-horizon?country=US' and retrieved_at = '2026-08-30T19:50:24Z'::timestamptz),
  '2026-08-31T09:30:00Z'::timestamptz, '2026-08-30T19:50:24Z'::timestamptz,
  '2026-08-30T19:50:24Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'caseThicknessMm', '3fdba35f04dc8c462986c992bcf875546257113072a909c162f7e470e581e278', (select id from public.sources where url = 'https://www.boldrsupply.co/products/odyssey-horizon?country=US' and retrieved_at = '2026-08-30T19:50:24Z'::timestamptz),
  '2026-08-31T09:30:00Z'::timestamptz, '2026-08-30T19:50:24Z'::timestamptz,
  '2026-08-30T19:50:24Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'lugToLugMm', '98010bd9270f9b100b6214a21754fd33bdc8d41b2bc9f9dd16ff54d3c34ffd71', (select id from public.sources where url = 'https://www.boldrsupply.co/products/odyssey-horizon?country=US' and retrieved_at = '2026-08-30T19:50:24Z'::timestamptz),
  '2026-08-31T09:30:00Z'::timestamptz, '2026-08-30T19:50:24Z'::timestamptz,
  '2026-08-30T19:50:24Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'lugWidthMm', 'f5ca38f748a1d6eaf726b8a42fb575c3c71f1864a8143301782de13da2d9202b', (select id from public.sources where url = 'https://www.boldrsupply.co/products/odyssey-horizon?country=US' and retrieved_at = '2026-08-30T19:50:24Z'::timestamptz),
  '2026-08-31T09:30:00Z'::timestamptz, '2026-08-30T19:50:24Z'::timestamptz,
  '2026-08-30T19:50:24Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'weightFullG', '1da51b8d8ff98f6a48f80ae79fe3ca6c26e1abb7b7d125259255d6d2b875ea08', (select id from public.sources where url = 'https://www.boldrsupply.co/products/odyssey-horizon?country=US' and retrieved_at = '2026-08-30T19:50:24Z'::timestamptz),
  '2026-08-31T09:30:00Z'::timestamptz, '2026-08-30T19:50:24Z'::timestamptz,
  '2026-08-30T19:50:24Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'movement', 'f6bc5a8f1c8cf3246df5d1edb394e1623fdf07ba8626d7f2400492152155cdbc', (select id from public.sources where url = 'https://www.boldrsupply.co/products/odyssey-horizon?country=US' and retrieved_at = '2026-08-30T19:50:24Z'::timestamptz),
  '2026-08-31T09:30:00Z'::timestamptz, '2026-08-30T19:50:24Z'::timestamptz,
  '2026-08-30T19:50:24Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'waterResistanceM', '983bd614bb5afece5ab3b6023f71147cd7b6bc2314f9d27af7422541c6558389', (select id from public.sources where url = 'https://www.boldrsupply.co/products/odyssey-horizon?country=US' and retrieved_at = '2026-08-30T19:50:24Z'::timestamptz),
  '2026-08-31T09:30:00Z'::timestamptz, '2026-08-30T19:50:24Z'::timestamptz,
  '2026-08-30T19:50:24Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'crownType', '2026fa400c91bf0e5fd82a1b3b951961bbb0fd2f862c4142a26aa6d59e82ce34', (select id from public.sources where url = 'https://www.boldrsupply.co/products/odyssey-horizon?country=US' and retrieved_at = '2026-08-30T19:50:24Z'::timestamptz),
  '2026-08-31T09:30:00Z'::timestamptz, '2026-08-30T19:50:24Z'::timestamptz,
  '2026-08-30T19:50:24Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'crystal', '7191152669ad73162c786dd51b4301ac95d94e7b053dea5f698bd2815785cfef', (select id from public.sources where url = 'https://www.boldrsupply.co/products/odyssey-horizon?country=US' and retrieved_at = '2026-08-30T19:50:24Z'::timestamptz),
  '2026-08-31T09:30:00Z'::timestamptz, '2026-08-30T19:50:24Z'::timestamptz,
  '2026-08-30T19:50:24Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'attachmentType', '4df9aae421e2338cea52d71dc8ec20fcd9a784086c5ac8c8a15aa8c0cd54495e', (select id from public.sources where url = 'https://www.boldrsupply.co/products/odyssey-horizon?country=US' and retrieved_at = '2026-08-30T19:50:24Z'::timestamptz),
  '2026-08-31T09:30:00Z'::timestamptz, '2026-08-30T19:50:24Z'::timestamptz,
  '2026-08-30T19:50:24Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'eligibleEnvironments', 'b5781120ccbc8985769d931d5d6c17ee6d65b33500903d8820d7f0520f8e0a65', (select id from public.sources where url = 'https://www.boldrsupply.co/products/odyssey-horizon?country=US' and retrieved_at = '2026-08-30T19:50:24Z'::timestamptz),
  '2026-08-31T09:30:00Z'::timestamptz, '2026-08-30T19:50:24Z'::timestamptz,
  '2026-08-30T19:50:24Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'ownershipFrictionLevels', '582066aec46a0e953a89b01aca2612ef776f66237e411fec8fb5f77652aaee62', (select id from public.sources where url = 'https://www.boldrsupply.co/products/odyssey-horizon?country=US' and retrieved_at = '2026-08-30T19:50:24Z'::timestamptz),
  '2026-08-31T09:30:00Z'::timestamptz, '2026-08-30T19:50:24Z'::timestamptz,
  '2026-08-30T19:50:24Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'traits', 'fa2f2d094851d236bc8c24c10ea871445bd9444d02783fcb373e5871d155c24a', (select id from public.sources where url = 'https://www.boldrsupply.co/products/odyssey-horizon?country=US' and retrieved_at = '2026-08-30T19:50:24Z'::timestamptz),
  '2026-08-31T09:30:00Z'::timestamptz, '2026-08-30T19:50:24Z'::timestamptz,
  '2026-08-30T19:50:24Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'identity', '253f4ebdb0bda0cdae7779ef0e3803109f5754d71962a0ceb8dde5be9117d85c', (select id from public.sources where url = 'https://www.boldrsupply.co/blogs/press-releases/dive-boldly-live-colorfully-the-odyssey-reimagined' and retrieved_at = '2026-08-30T19:50:24Z'::timestamptz),
  '2026-08-31T09:30:00Z'::timestamptz, '2026-08-30T19:50:24Z'::timestamptz,
  '2026-08-30T19:50:24Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'complications', '8b412b06fe22ce7b5db869378d6126533d73a08ad09d3930983adae376bd5ea3', (select id from public.sources where url = 'https://www.boldrsupply.co/blogs/press-releases/dive-boldly-live-colorfully-the-odyssey-reimagined' and retrieved_at = '2026-08-30T19:50:24Z'::timestamptz),
  '2026-08-31T09:30:00Z'::timestamptz, '2026-08-30T19:50:24Z'::timestamptz,
  '2026-08-30T19:50:24Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'dateStatus', '94332144d941eb1212c9af7f968e215a7042bf94925c9c10b21de97a2f0cea06', (select id from public.sources where url = 'https://www.boldrsupply.co/blogs/press-releases/dive-boldly-live-colorfully-the-odyssey-reimagined' and retrieved_at = '2026-08-30T19:50:24Z'::timestamptz),
  '2026-08-31T09:30:00Z'::timestamptz, '2026-08-30T19:50:24Z'::timestamptz,
  '2026-08-30T19:50:24Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'movement', 'f6bc5a8f1c8cf3246df5d1edb394e1623fdf07ba8626d7f2400492152155cdbc', (select id from public.sources where url = 'https://miyotamovement.com/product/9075/' and retrieved_at = '2026-08-30T19:50:24Z'::timestamptz),
  '2026-08-31T09:30:00Z'::timestamptz, '2026-08-30T19:50:24Z'::timestamptz,
  '2026-08-30T19:50:24Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'accuracy', '934af4819d552af4866b3ab6ae953f0592e1b68b2b194c57ea399005ed5265e9', (select id from public.sources where url = 'https://miyotamovement.com/product/9075/' and retrieved_at = '2026-08-30T19:50:24Z'::timestamptz),
  '2026-08-31T09:30:00Z'::timestamptz, '2026-08-30T19:50:24Z'::timestamptz,
  '2026-08-30T19:50:24Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'identity', '253f4ebdb0bda0cdae7779ef0e3803109f5754d71962a0ceb8dde5be9117d85c', (select id from public.sources where url = 'https://wornandwound.com/review/hands-on-the-new-boldr-odyssey/' and retrieved_at = '2026-08-31T09:30:00Z'::timestamptz),
  '2026-08-31T09:30:00Z'::timestamptz, '2026-08-31T09:30:00Z'::timestamptz,
  '2026-08-31T09:30:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'lumeGrade', 'ec109d66b0e82ab98ada5f28fa8bf34dda5beff3f384e5f1a5f8bc2c3ba63a3c', (select id from public.sources where url = 'https://wornandwound.com/review/hands-on-the-new-boldr-odyssey/' and retrieved_at = '2026-08-31T09:30:00Z'::timestamptz),
  '2026-08-31T09:30:00Z'::timestamptz, '2026-08-31T09:30:00Z'::timestamptz,
  '2026-08-31T09:30:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';



insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, stale_after, tier, reviewer
)
select 'price_snapshot', ps.id, 'amount_low_minor', 'a391883afaafc16565d31d84e2c9eddb614cc0f2238c3fa2a2889d825a06e63c', (select id from public.sources where url = 'https://www.boldrsupply.co/products/odyssey-horizon?country=US' and retrieved_at = '2026-08-30T19:50:24Z'::timestamptz),
  ps.observed_at, '2026-08-30T19:50:24Z'::timestamptz,
  '2026-08-30T19:50:24Z'::timestamptz,
  ps.stale_after, 'verified', 'catalogue-expansion-v1'
from public.price_snapshots ps
where ps.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt')
  and ps.kind = 'retail' and ps.condition = 'new'
  and ps.currency = 'USD'
  and ps.observed_at = '2026-08-31T09:30:00Z'::timestamptz
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, stale_after = excluded.stale_after,
  tier = 'verified', reviewer = 'catalogue-expansion-v1';



insert into public.completeness_evaluations (
  subject_type, subject_id, level, filter_contract_version, complete,
  completeness_score, missing_fields, evaluated_at
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'm0', 1,
  true, 1.0000, array[]::text[],
  '2026-08-31T09:30:00Z'::timestamptz
)
on conflict (subject_type, subject_id, level, filter_contract_version) do update set
  complete = excluded.complete,
  completeness_score = excluded.completeness_score,
  missing_fields = excluded.missing_fields,
  evaluated_at = excluded.evaluated_at;

insert into public.completeness_evaluations (
  subject_type, subject_id, level, filter_contract_version, complete,
  completeness_score, missing_fields, evaluated_at
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'm1', 1,
  true, 1.0000, array[]::text[],
  '2026-08-31T09:30:00Z'::timestamptz
)
on conflict (subject_type, subject_id, level, filter_contract_version) do update set
  complete = excluded.complete,
  completeness_score = excluded.completeness_score,
  missing_fields = excluded.missing_fields,
  evaluated_at = excluded.evaluated_at;

insert into public.completeness_evaluations (
  subject_type, subject_id, level, filter_contract_version, complete,
  completeness_score, missing_fields, evaluated_at
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'boldr' and rv.variant_key = 'boldr-odyssey-horizon-druber-gmt'), 'm2', 1,
  false, 0.6667, array['market']::text[],
  '2026-08-31T09:30:00Z'::timestamptz
)
on conflict (subject_type, subject_id, level, filter_contract_version) do update set
  complete = excluded.complete,
  completeness_score = excluded.completeness_score,
  missing_fields = excluded.missing_fields,
  evaluated_at = excluded.evaluated_at;
