-- Generated by scripts/render-seed-migration.ts from the reviewed seed bundle.
-- Additive expansion for: rolex-124060, rolex-126600.

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.rolex.com/en-us/watches/submariner/m124060-0001', 'https://www.rolex.com/en-us/watches/submariner/m124060-0001', 'Rolex Submariner Oystersteel — reference 124060', 'Rolex', 'manufacturer_product', '2026-08-31T17:45:00Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.bobswatches.com/rolex-blog/watch-101/rolex-watch-case-size.html', 'https://www.bobswatches.com/rolex-blog/watch-101/rolex-watch-case-size.html', 'Rolex current-reference thickness, lug-to-lug, and weight measurements', 'Bob''s Watches', 'secondary_editorial', '2026-08-31T17:45:00Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://superlativewatchco.com/pages/rolex-weight-guide', 'https://superlativewatchco.com/pages/rolex-weight-guide', 'Rolex 2026 exact-reference full-link weight controls', 'Superlative Watch Co.', 'secondary_editorial', '2026-08-31T17:45:00Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.everestbands.com/products/rolex-submariner-produced-after-2020-1-5mm-spring-bars', 'https://www.everestbands.com/products/rolex-submariner-produced-after-2020-1-5mm-spring-bars', 'Rolex Submariner 124060 replacement spring-bar fitment', 'Everest Bands', 'secondary_editorial', '2026-08-31T17:45:00Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.rolex.com/en-us/watches/sea-dweller/m126600-0002', 'https://www.rolex.com/en-us/watches/sea-dweller/m126600-0002', 'Rolex Sea-Dweller Oystersteel — reference 126600', 'Rolex', 'manufacturer_product', '2026-08-31T17:45:00Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.everestbands.com/blogs/bezel-barrel/guide-to-rolex-sizes-case-and-lug-dimensions-by-reference', 'https://www.everestbands.com/blogs/bezel-barrel/guide-to-rolex-sizes-case-and-lug-dimensions-by-reference', 'Rolex case and lug dimensions by reference', 'Everest Bands', 'secondary_editorial', '2026-08-31T17:45:00Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.sources
  (url, canonical_url, title, publisher, source_type, retrieved_at)
values
  ('https://www.everestbands.com/products/curved-end-rubber-strap-for-rolex-sea-dweller-43mm-126600-tang', 'https://www.everestbands.com/products/curved-end-rubber-strap-for-rolex-sea-dweller-43mm-126600-tang', 'Rolex Sea-Dweller 126600 spring-bar strap fitment', 'Everest Bands', 'secondary_editorial', '2026-08-31T17:45:00Z'::timestamptz)
on conflict (url, retrieved_at) do update set
  canonical_url = excluded.canonical_url,
  title = excluded.title,
  publisher = excluded.publisher,
  source_type = excluded.source_type;

insert into public.brands (slug, name, review_status)
values ('rolex', 'Rolex', 'accepted')
on conflict (slug) do update set name = excluded.name, review_status = 'accepted', updated_at = now();

insert into public.collections (brand_id, slug, name, review_status)
select id, 'submariner', 'Submariner', 'accepted'
from public.brands where slug = 'rolex'
on conflict (brand_id, slug) do update set name = excluded.name, review_status = 'accepted', updated_at = now();

insert into public.collections (brand_id, slug, name, review_status)
select id, 'sea-dweller', 'Sea-Dweller', 'accepted'
from public.brands where slug = 'rolex'
on conflict (brand_id, slug) do update set name = excluded.name, review_status = 'accepted', updated_at = now();

insert into public.reference_models (collection_id, slug, model_name, review_status)
select c.id, 'submariner', 'Submariner', 'accepted'
from public.collections c join public.brands b on b.id = c.brand_id
where b.slug = 'rolex' and c.slug = 'submariner'
on conflict (collection_id, slug) do update set model_name = excluded.model_name, review_status = 'accepted', updated_at = now();

insert into public.reference_models (collection_id, slug, model_name, review_status)
select c.id, 'sea-dweller-43', 'Sea-Dweller 43', 'accepted'
from public.collections c join public.brands b on b.id = c.brand_id
where b.slug = 'rolex' and c.slug = 'sea-dweller'
on conflict (collection_id, slug) do update set model_name = excluded.model_name, review_status = 'accepted', updated_at = now();

insert into public.reference_variants (
  reference_model_id, variant_key, reference_code, variant_name,
  case_material, caseback_material, bracelet_material, strap_material,
  nickel_contact_risk, case_diameter_mm, case_width_mm, case_length_mm,
  case_thickness_mm, lug_to_lug_mm,
  lug_to_lug_measured, lug_width_mm, lug_curvature, integrated_bracelet,
  weight_full_g, movement_type, caliber_ref, power_reserve_h,
  accuracy_lower_seconds, accuracy_upper_seconds, accuracy_period_days,
  water_resistance_m, crown_type, crown_position, crystal, lume_grade,
  bracelet_attachment, shock_resistant, production_status, review_status
)
values (
  (select rm.id from public.reference_models rm join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and c.slug = 'submariner' and rm.slug = 'submariner'), 'rolex-124060', '124060', 'Oystersteel · black dial · Oyster bracelet',
  'Oystersteel', 'Oystersteel', 'Oystersteel Oyster bracelet', null,
  null, 41, null, null,
  12.5, 47.6,
  true, 21, null, false,
  158.8, 'automatic', '3230', 70,
  -2, 2, 1,
  300, 'screw_down', '3', 'sapphire', 'strong',
  'spring_bar', true, 'current', 'accepted'
)
on conflict (reference_model_id, variant_key) do update set
  reference_code = excluded.reference_code,
  variant_name = excluded.variant_name,
  case_material = excluded.case_material,
  caseback_material = excluded.caseback_material,
  bracelet_material = excluded.bracelet_material,
  strap_material = excluded.strap_material,
  nickel_contact_risk = excluded.nickel_contact_risk,
  case_diameter_mm = excluded.case_diameter_mm,
  case_width_mm = excluded.case_width_mm,
  case_length_mm = excluded.case_length_mm,
  case_thickness_mm = excluded.case_thickness_mm,
  lug_to_lug_mm = excluded.lug_to_lug_mm,
  lug_to_lug_measured = excluded.lug_to_lug_measured,
  lug_width_mm = excluded.lug_width_mm,
  lug_curvature = excluded.lug_curvature,
  integrated_bracelet = excluded.integrated_bracelet,
  weight_full_g = excluded.weight_full_g,
  movement_type = excluded.movement_type,
  caliber_ref = excluded.caliber_ref,
  power_reserve_h = excluded.power_reserve_h,
  accuracy_lower_seconds = excluded.accuracy_lower_seconds,
  accuracy_upper_seconds = excluded.accuracy_upper_seconds,
  accuracy_period_days = excluded.accuracy_period_days,
  water_resistance_m = excluded.water_resistance_m,
  crown_type = excluded.crown_type,
  crown_position = excluded.crown_position,
  crystal = excluded.crystal,
  lume_grade = excluded.lume_grade,
  bracelet_attachment = excluded.bracelet_attachment,
  shock_resistant = excluded.shock_resistant,
  production_status = excluded.production_status,
  review_status = 'accepted',
  updated_at = now();

insert into public.reference_variants (
  reference_model_id, variant_key, reference_code, variant_name,
  case_material, caseback_material, bracelet_material, strap_material,
  nickel_contact_risk, case_diameter_mm, case_width_mm, case_length_mm,
  case_thickness_mm, lug_to_lug_mm,
  lug_to_lug_measured, lug_width_mm, lug_curvature, integrated_bracelet,
  weight_full_g, movement_type, caliber_ref, power_reserve_h,
  accuracy_lower_seconds, accuracy_upper_seconds, accuracy_period_days,
  water_resistance_m, crown_type, crown_position, crystal, lume_grade,
  bracelet_attachment, shock_resistant, production_status, review_status
)
values (
  (select rm.id from public.reference_models rm join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and c.slug = 'sea-dweller' and rm.slug = 'sea-dweller-43'), 'rolex-126600', '126600', 'Oystersteel · intense black dial · Oyster bracelet',
  'Oystersteel', 'Oystersteel', 'Oystersteel Oyster bracelet with Glidelock', null,
  null, 43, null, null,
  15, 51,
  true, 22, null, false,
  194, 'automatic', '3235', 70,
  -2, 2, 1,
  1220, 'screw_down', '3', 'sapphire', 'strong',
  'spring_bar', true, 'current', 'accepted'
)
on conflict (reference_model_id, variant_key) do update set
  reference_code = excluded.reference_code,
  variant_name = excluded.variant_name,
  case_material = excluded.case_material,
  caseback_material = excluded.caseback_material,
  bracelet_material = excluded.bracelet_material,
  strap_material = excluded.strap_material,
  nickel_contact_risk = excluded.nickel_contact_risk,
  case_diameter_mm = excluded.case_diameter_mm,
  case_width_mm = excluded.case_width_mm,
  case_length_mm = excluded.case_length_mm,
  case_thickness_mm = excluded.case_thickness_mm,
  lug_to_lug_mm = excluded.lug_to_lug_mm,
  lug_to_lug_measured = excluded.lug_to_lug_measured,
  lug_width_mm = excluded.lug_width_mm,
  lug_curvature = excluded.lug_curvature,
  integrated_bracelet = excluded.integrated_bracelet,
  weight_full_g = excluded.weight_full_g,
  movement_type = excluded.movement_type,
  caliber_ref = excluded.caliber_ref,
  power_reserve_h = excluded.power_reserve_h,
  accuracy_lower_seconds = excluded.accuracy_lower_seconds,
  accuracy_upper_seconds = excluded.accuracy_upper_seconds,
  accuracy_period_days = excluded.accuracy_period_days,
  water_resistance_m = excluded.water_resistance_m,
  crown_type = excluded.crown_type,
  crown_position = excluded.crown_position,
  crystal = excluded.crystal,
  lume_grade = excluded.lume_grade,
  bracelet_attachment = excluded.bracelet_attachment,
  shock_resistant = excluded.shock_resistant,
  production_status = excluded.production_status,
  review_status = 'accepted',
  updated_at = now();

update public.reference_variants
set product_url = 'https://www.rolex.com/en-us/watches/submariner/m124060-0001', updated_at = now()
where id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060')
  and product_url is distinct from 'https://www.rolex.com/en-us/watches/submariner/m124060-0001';

update public.reference_variants
set product_url = 'https://www.rolex.com/en-us/watches/sea-dweller/m126600-0002', updated_at = now()
where id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600')
  and product_url is distinct from 'https://www.rolex.com/en-us/watches/sea-dweller/m126600-0002';

insert into public.reference_complications (reference_variant_id, complication)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'date')
on conflict (reference_variant_id, complication) do nothing;

insert into public.price_snapshots (
  reference_variant_id, kind, condition, currency, amount_low_minor,
  market_country_code, observed_at, stale_after, review_status
)
select (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'retail', 'new', 'USD', 1005000,
  'US', '2026-08-31T17:45:00Z'::timestamptz, '2027-02-27T17:45:00Z'::timestamptz, 'accepted'
where not exists (
  select 1 from public.price_snapshots ps
  where ps.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060')
    and ps.kind = 'retail' and ps.condition = 'new'
    and ps.currency = 'USD'
    and ps.observed_at = '2026-08-31T17:45:00Z'::timestamptz
);

insert into public.price_snapshots (
  reference_variant_id, kind, condition, currency, amount_low_minor,
  market_country_code, observed_at, stale_after, review_status
)
select (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'retail', 'new', 'USD', 1455000,
  'US', '2026-08-31T17:45:00Z'::timestamptz, '2027-02-27T17:45:00Z'::timestamptz, 'accepted'
where not exists (
  select 1 from public.price_snapshots ps
  where ps.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600')
    and ps.kind = 'retail' and ps.condition = 'new'
    and ps.currency = 'USD'
    and ps.observed_at = '2026-08-31T17:45:00Z'::timestamptz
);



insert into public.reference_deployment_profiles (
  reference_variant_id, environment, review_status
)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'field_water_abuse', 'accepted')
on conflict (reference_variant_id, environment) do update set
  review_status = 'accepted';

insert into public.reference_deployment_profiles (
  reference_variant_id, environment, review_status
)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'studio_desk_daily', 'accepted')
on conflict (reference_variant_id, environment) do update set
  review_status = 'accepted';

insert into public.reference_deployment_profiles (
  reference_variant_id, environment, review_status
)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'field_water_abuse', 'accepted')
on conflict (reference_variant_id, environment) do update set
  review_status = 'accepted';

insert into public.reference_ownership_friction_profiles (
  reference_variant_id, friction_level, review_status
)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'workhorse_mechanical', 'accepted')
on conflict (reference_variant_id, friction_level) do update set
  review_status = 'accepted';

insert into public.reference_ownership_friction_profiles (
  reference_variant_id, friction_level, review_status
)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'workhorse_mechanical', 'accepted')
on conflict (reference_variant_id, friction_level) do update set
  review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'primary_archetype', 'benchmark_dive_watch', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'social_signal', 'unapologetic_benchmark', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'aesthetic_dna', 'structural_tool', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'emotional_objective', 'dependability', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'emotional_objective', 'milestone', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'primary_archetype', 'professional_saturation_diver', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'social_signal', 'unapologetic_benchmark', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'aesthetic_dna', 'structural_tool', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'emotional_objective', 'dependability', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.reference_traits (reference_variant_id, axis, value, weight, review_status)
values ((select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'emotional_objective', 'milestone', 1, 'accepted')
on conflict (reference_variant_id, axis, value) do update set weight = 1, review_status = 'accepted';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'identity', 'ee3e3a95fbe9723b1350728fed8c2911ef67632e65436c78f5d93ea063b611fc', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/submariner/m124060-0001' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'materials', '77e46ec14273a801da34997541d4414b69fc4a5fb0c757fc0194431d8c4a9b2d', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/submariner/m124060-0001' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'productionStatus', '694df57a7909d9f9edbd3acb4ccfce5fbee156fab749383121f17fef16bbab57', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/submariner/m124060-0001' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'caseDiameterMm', '3d914f9348c9cc0ff8a79716700b9fcd4d2f3e711608004eb8f138bcba7f14d9', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/submariner/m124060-0001' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'movement', '8932fc7f3e2861868cb1111b122c74c75900eaf8e0fbbc4872fd6962afb3fcd8', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/submariner/m124060-0001' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'accuracy', '6b43dda1f7f5b56184d508ab7b971fa5e8310c7a5a724e2bf4d4e30bcfc33e90', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/submariner/m124060-0001' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'waterResistanceM', '983bd614bb5afece5ab3b6023f71147cd7b6bc2314f9d27af7422541c6558389', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/submariner/m124060-0001' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'crownType', '2026fa400c91bf0e5fd82a1b3b951961bbb0fd2f862c4142a26aa6d59e82ce34', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/submariner/m124060-0001' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'crystal', '7191152669ad73162c786dd51b4301ac95d94e7b053dea5f698bd2815785cfef', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/submariner/m124060-0001' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'lumeGrade', 'ec109d66b0e82ab98ada5f28fa8bf34dda5beff3f384e5f1a5f8bc2c3ba63a3c', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/submariner/m124060-0001' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'complications', '4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/submariner/m124060-0001' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'dateStatus', '15dbb2c4361b809a46b847b3b6c071f3c27c096057d31c45351902b79fe39efd', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/submariner/m124060-0001' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'eligibleEnvironments', 'b5781120ccbc8985769d931d5d6c17ee6d65b33500903d8820d7f0520f8e0a65', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/submariner/m124060-0001' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'ownershipFrictionLevels', '582066aec46a0e953a89b01aca2612ef776f66237e411fec8fb5f77652aaee62', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/submariner/m124060-0001' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'traits', '52562177e16b2f36762f79e3fff917f05bffe3d03dbaa6adf04afcf59d85af15', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/submariner/m124060-0001' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'caseThicknessMm', 'b902cc4550838229a710bfec4c38cbc7eb11082367a409df9135e7f007a96bda', (select id from public.sources where url = 'https://www.bobswatches.com/rolex-blog/watch-101/rolex-watch-case-size.html' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'lugToLugMm', 'a4367ec7423625a19d0864f48e761d0eaa4b9141d2338514758d0ae420e837fa', (select id from public.sources where url = 'https://www.bobswatches.com/rolex-blog/watch-101/rolex-watch-case-size.html' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'weightFullG', '28616f3712963ee6839cfc663f3a876aa96e77563cc7864b7bf737e217b158df', (select id from public.sources where url = 'https://superlativewatchco.com/pages/rolex-weight-guide' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'lugWidthMm', '6f4b6612125fb3a0daecd2799dfd6c9c299424fd920f9b308110a2c1fbd8f443', (select id from public.sources where url = 'https://www.everestbands.com/products/rolex-submariner-produced-after-2020-1-5mm-spring-bars' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'attachmentType', 'dc8f261bad159c55d8fb5a6cdf75774951c242716e8306aaaad0e1a7b999db27', (select id from public.sources where url = 'https://www.everestbands.com/products/rolex-submariner-produced-after-2020-1-5mm-spring-bars' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'identity', 'bdabb23b587aeda3f8cd7a0c5b25aceed824bdf3e138d1def34eee9b60cfd7f0', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/sea-dweller/m126600-0002' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'materials', 'ca68f5300188aa783fc1ed5397295c6531ff4d8e494afd6d5e843dfb7c4b2c3a', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/sea-dweller/m126600-0002' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'productionStatus', '694df57a7909d9f9edbd3acb4ccfce5fbee156fab749383121f17fef16bbab57', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/sea-dweller/m126600-0002' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'caseDiameterMm', '44cb730c420480a0477b505ae68af508fb90f96cf0ec54c6ad16949dd427f13a', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/sea-dweller/m126600-0002' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'movement', '2b745fb6c59db30a4b3e91997d85e3451796566a3d2cb7497ec22dde48457f88', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/sea-dweller/m126600-0002' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'accuracy', '6b43dda1f7f5b56184d508ab7b971fa5e8310c7a5a724e2bf4d4e30bcfc33e90', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/sea-dweller/m126600-0002' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'waterResistanceM', 'f79b8977720743f5e7c8b5b2e3813a8a4cc9aacd97eb20fcf41a7169e66ec1b9', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/sea-dweller/m126600-0002' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'crownType', '2026fa400c91bf0e5fd82a1b3b951961bbb0fd2f862c4142a26aa6d59e82ce34', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/sea-dweller/m126600-0002' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'crystal', '7191152669ad73162c786dd51b4301ac95d94e7b053dea5f698bd2815785cfef', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/sea-dweller/m126600-0002' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'lumeGrade', 'ec109d66b0e82ab98ada5f28fa8bf34dda5beff3f384e5f1a5f8bc2c3ba63a3c', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/sea-dweller/m126600-0002' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'complications', '4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/sea-dweller/m126600-0002' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'dateStatus', '94332144d941eb1212c9af7f968e215a7042bf94925c9c10b21de97a2f0cea06', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/sea-dweller/m126600-0002' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'eligibleEnvironments', '7081e94de70b2f62f36ef290dfc10647593c1e0d8e98bc076d357adbc5b27491', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/sea-dweller/m126600-0002' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'ownershipFrictionLevels', '582066aec46a0e953a89b01aca2612ef776f66237e411fec8fb5f77652aaee62', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/sea-dweller/m126600-0002' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'traits', 'b0aecc21f48d06d9b6c0748afcb67f4902b47cbe122ff4a63c7dff0eb842e99e', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/sea-dweller/m126600-0002' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'caseThicknessMm', 'e629fa6598d732768f7c726b4b621285f9c3b85303900aa912017db7617d8bdb', (select id from public.sources where url = 'https://www.bobswatches.com/rolex-blog/watch-101/rolex-watch-case-size.html' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'lugToLugMm', '031b4af5197ec30a926f48cf40e11a7dbc470048a21e4003b7a3c07c5dab1baa', (select id from public.sources where url = 'https://www.bobswatches.com/rolex-blog/watch-101/rolex-watch-case-size.html' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'weightFullG', '7559ca4a957c8c82ba04781cd66a68d6022229fca0e8e88d8e487c96ee4446d0', (select id from public.sources where url = 'https://superlativewatchco.com/pages/rolex-weight-guide' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'lugWidthMm', '785f3ec7eb32f30b90cd0fcf3657d388b5ff4297f2f9716ff66e9b69c05ddd09', (select id from public.sources where url = 'https://www.everestbands.com/blogs/bezel-barrel/guide-to-rolex-sizes-case-and-lug-dimensions-by-reference' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, tier, reviewer
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'attachmentType', 'dc8f261bad159c55d8fb5a6cdf75774951c242716e8306aaaad0e1a7b999db27', (select id from public.sources where url = 'https://www.everestbands.com/products/curved-end-rubber-strap-for-rolex-sea-dweller-43mm-126600-tang' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  '2026-08-31T17:45:00Z'::timestamptz, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz, 'verified', 'catalogue-expansion-v1'
)
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, tier = 'verified', reviewer = 'catalogue-expansion-v1';



insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, stale_after, tier, reviewer
)
select 'price_snapshot', ps.id, 'amount_low_minor', 'f64d9b7af447a954e35215959a4b2dd86adc843a0ce7da1deb5db8d89c5c3594', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/submariner/m124060-0001' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  ps.observed_at, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz,
  ps.stale_after, 'verified', 'catalogue-expansion-v1'
from public.price_snapshots ps
where ps.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060')
  and ps.kind = 'retail' and ps.condition = 'new'
  and ps.currency = 'USD'
  and ps.observed_at = '2026-08-31T17:45:00Z'::timestamptz
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, stale_after = excluded.stale_after,
  tier = 'verified', reviewer = 'catalogue-expansion-v1';

insert into public.field_evidence (
  subject_type, subject_id, field_name, value_hash, source_id,
  observed_at, retrieved_at, verified_at, stale_after, tier, reviewer
)
select 'price_snapshot', ps.id, 'amount_low_minor', '26769f1a23e33eb4c2b484e1ee982758964e27b929f1c4d076aa2d204f44691f', (select id from public.sources where url = 'https://www.rolex.com/en-us/watches/sea-dweller/m126600-0002' and retrieved_at = '2026-08-31T17:45:00Z'::timestamptz),
  ps.observed_at, '2026-08-31T17:45:00Z'::timestamptz,
  '2026-08-31T17:45:00Z'::timestamptz,
  ps.stale_after, 'verified', 'catalogue-expansion-v1'
from public.price_snapshots ps
where ps.reference_variant_id = (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600')
  and ps.kind = 'retail' and ps.condition = 'new'
  and ps.currency = 'USD'
  and ps.observed_at = '2026-08-31T17:45:00Z'::timestamptz
on conflict (subject_type, subject_id, field_name, value_hash, source_id) do update set
  verified_at = excluded.verified_at, stale_after = excluded.stale_after,
  tier = 'verified', reviewer = 'catalogue-expansion-v1';



insert into public.completeness_evaluations (
  subject_type, subject_id, level, filter_contract_version, complete,
  completeness_score, missing_fields, evaluated_at
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'm0', 1,
  true, 1.0000, array[]::text[],
  '2026-08-31T17:45:00Z'::timestamptz
)
on conflict (subject_type, subject_id, level, filter_contract_version) do update set
  complete = excluded.complete,
  completeness_score = excluded.completeness_score,
  missing_fields = excluded.missing_fields,
  evaluated_at = excluded.evaluated_at;

insert into public.completeness_evaluations (
  subject_type, subject_id, level, filter_contract_version, complete,
  completeness_score, missing_fields, evaluated_at
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'm1', 1,
  true, 1.0000, array[]::text[],
  '2026-08-31T17:45:00Z'::timestamptz
)
on conflict (subject_type, subject_id, level, filter_contract_version) do update set
  complete = excluded.complete,
  completeness_score = excluded.completeness_score,
  missing_fields = excluded.missing_fields,
  evaluated_at = excluded.evaluated_at;

insert into public.completeness_evaluations (
  subject_type, subject_id, level, filter_contract_version, complete,
  completeness_score, missing_fields, evaluated_at
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-124060'), 'm2', 1,
  false, 0.6667, array['market']::text[],
  '2026-08-31T17:45:00Z'::timestamptz
)
on conflict (subject_type, subject_id, level, filter_contract_version) do update set
  complete = excluded.complete,
  completeness_score = excluded.completeness_score,
  missing_fields = excluded.missing_fields,
  evaluated_at = excluded.evaluated_at;

insert into public.completeness_evaluations (
  subject_type, subject_id, level, filter_contract_version, complete,
  completeness_score, missing_fields, evaluated_at
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'm0', 1,
  true, 1.0000, array[]::text[],
  '2026-08-31T17:45:00Z'::timestamptz
)
on conflict (subject_type, subject_id, level, filter_contract_version) do update set
  complete = excluded.complete,
  completeness_score = excluded.completeness_score,
  missing_fields = excluded.missing_fields,
  evaluated_at = excluded.evaluated_at;

insert into public.completeness_evaluations (
  subject_type, subject_id, level, filter_contract_version, complete,
  completeness_score, missing_fields, evaluated_at
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'm1', 1,
  true, 1.0000, array[]::text[],
  '2026-08-31T17:45:00Z'::timestamptz
)
on conflict (subject_type, subject_id, level, filter_contract_version) do update set
  complete = excluded.complete,
  completeness_score = excluded.completeness_score,
  missing_fields = excluded.missing_fields,
  evaluated_at = excluded.evaluated_at;

insert into public.completeness_evaluations (
  subject_type, subject_id, level, filter_contract_version, complete,
  completeness_score, missing_fields, evaluated_at
)
values (
  'reference_variant', (select rv.id from public.reference_variants rv join public.reference_models rm on rm.id = rv.reference_model_id join public.collections c on c.id = rm.collection_id join public.brands b on b.id = c.brand_id where b.slug = 'rolex' and rv.variant_key = 'rolex-126600'), 'm2', 1,
  false, 0.6667, array['market']::text[],
  '2026-08-31T17:45:00Z'::timestamptz
)
on conflict (subject_type, subject_id, level, filter_contract_version) do update set
  complete = excluded.complete,
  completeness_score = excluded.completeness_score,
  missing_fields = excluded.missing_fields,
  evaluated_at = excluded.evaluated_at;
