-- Partner sites (owner decision, 2026-10-04). Additive only.
--
-- Paying partners put The Reserve's features on their own websites: a
-- script tag, a WordPress or Shopify plugin, or the JSON API. Each site has
-- a public key (pk_live_…, safe in page source), an optional secret key for
-- server-to-server API calls (stored only as a SHA-256 hash), the website
-- addresses allowed to show the features, an optional monthly limit and a
-- theme. Sites are switched off, never deleted.
--
-- partner_site_usage counts uses per site, month and feature, for invoices
-- and the optional monthly limit. No visitor data is stored.

create table private.partner_sites (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 120),
  public_key text not null unique check (public_key ~ '^pk_live_[A-Za-z0-9]{24}$'),
  secret_key_hash text check (secret_key_hash is null or secret_key_hash ~ '^[0-9a-f]{64}$'),
  allowed_origins text[] not null default '{}',
  active boolean not null default true,
  monthly_quota integer check (monthly_quota is null or monthly_quota > 0),
  theme jsonb not null default '{}'::jsonb check (jsonb_typeof(theme) = 'object'),
  notes text check (notes is null or char_length(notes) <= 500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index partner_sites_secret_idx on private.partner_sites (secret_key_hash)
  where secret_key_hash is not null;

alter table private.partner_sites enable row level security;

create table private.partner_site_usage (
  site_id uuid not null references private.partner_sites (id),
  month date not null check (month = date_trunc('month', month)::date),
  feature text not null check (feature in ('archetype', 'quiz', 'find', 'alternatives', 'stories')),
  uses integer not null default 0 check (uses >= 0),
  primary key (site_id, month, feature)
);

alter table private.partner_site_usage enable row level security;

create function private.partner_site_json(s private.partner_sites)
returns jsonb
language sql
stable
set search_path = ''
as $$
  select jsonb_build_object(
    'id', s.id,
    'name', s.name,
    'publicKey', s.public_key,
    'hasSecret', s.secret_key_hash is not null,
    'allowedOrigins', to_jsonb(s.allowed_origins),
    'active', s.active,
    'monthlyQuota', s.monthly_quota,
    'theme', s.theme,
    'notes', s.notes,
    'createdAt', s.created_at,
    'updatedAt', s.updated_at
  );
$$;

create function public.partner_site_by_public_key_v1(p_key text)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select private.partner_site_json(s) from private.partner_sites s where s.public_key = p_key;
$$;

create function public.partner_site_by_secret_v1(p_hash text)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select private.partner_site_json(s) from private.partner_sites s where s.secret_key_hash = p_hash;
$$;

-- Every site with its uses this month and last month, per feature.
create function public.partner_sites_list_v1()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(jsonb_agg(
    private.partner_site_json(s) || jsonb_build_object(
      'usage', coalesce((
        select jsonb_agg(jsonb_build_object('month', u.month, 'feature', u.feature, 'uses', u.uses)
                         order by u.month desc, u.feature)
        from private.partner_site_usage u
        where u.site_id = s.id
          and u.month >= (date_trunc('month', now()) - interval '1 month')::date
      ), '[]'::jsonb)
    ) order by s.created_at desc
  ), '[]'::jsonb)
  from private.partner_sites s;
$$;

-- Creates a site (no id) or updates one. Keys are generated by the server.
create function public.partner_site_save_v1(p_site jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  saved private.partner_sites;
begin
  if p_site ? 'id' and p_site->>'id' is not null then
    update private.partner_sites set
      name = p_site->>'name',
      allowed_origins = array(select jsonb_array_elements_text(p_site->'allowedOrigins')),
      active = (p_site->>'active')::boolean,
      monthly_quota = (p_site->>'monthlyQuota')::integer,
      theme = coalesce(p_site->'theme', '{}'::jsonb),
      notes = p_site->>'notes',
      updated_at = now()
    where id = (p_site->>'id')::uuid
    returning * into saved;
  else
    insert into private.partner_sites (name, public_key, allowed_origins, active, monthly_quota, theme, notes)
    values (
      p_site->>'name',
      p_site->>'publicKey',
      array(select jsonb_array_elements_text(p_site->'allowedOrigins')),
      coalesce((p_site->>'active')::boolean, true),
      (p_site->>'monthlyQuota')::integer,
      coalesce(p_site->'theme', '{}'::jsonb),
      p_site->>'notes'
    )
    returning * into saved;
  end if;
  return case when saved.id is null then null else private.partner_site_json(saved) end;
end;
$$;

create function public.partner_site_set_secret_v1(p_id uuid, p_hash text)
returns boolean
language sql
security definer
set search_path = ''
as $$
  update private.partner_sites
  set secret_key_hash = p_hash, updated_at = now()
  where id = p_id
  returning true;
$$;

-- Counts one use unless the site's monthly limit is already reached.
create function public.partner_site_use_v1(p_site uuid, p_feature text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  this_month date := date_trunc('month', now())::date;
  quota integer;
  used integer;
begin
  select s.monthly_quota into quota
  from private.partner_sites s
  where s.id = p_site and s.active
  for update;
  if not found then
    return jsonb_build_object('allowed', false, 'uses', 0);
  end if;
  select coalesce(sum(u.uses), 0) into used
  from private.partner_site_usage u
  where u.site_id = p_site and u.month = this_month;
  if quota is not null and used >= quota then
    return jsonb_build_object('allowed', false, 'uses', used);
  end if;
  insert into private.partner_site_usage (site_id, month, feature, uses)
  values (p_site, this_month, p_feature, 1)
  on conflict (site_id, month, feature) do update set uses = private.partner_site_usage.uses + 1;
  return jsonb_build_object('allowed', true, 'uses', used + 1);
end;
$$;

revoke all on function private.partner_site_json(private.partner_sites) from public, anon, authenticated;
revoke all on function public.partner_site_by_public_key_v1(text) from public, anon, authenticated;
revoke all on function public.partner_site_by_secret_v1(text) from public, anon, authenticated;
revoke all on function public.partner_sites_list_v1() from public, anon, authenticated;
revoke all on function public.partner_site_save_v1(jsonb) from public, anon, authenticated;
revoke all on function public.partner_site_set_secret_v1(uuid, text) from public, anon, authenticated;
revoke all on function public.partner_site_use_v1(uuid, text) from public, anon, authenticated;
grant execute on function public.partner_site_by_public_key_v1(text) to service_role;
grant execute on function public.partner_site_by_secret_v1(text) to service_role;
grant execute on function public.partner_sites_list_v1() to service_role;
grant execute on function public.partner_site_save_v1(jsonb) to service_role;
grant execute on function public.partner_site_set_secret_v1(uuid, text) to service_role;
grant execute on function public.partner_site_use_v1(uuid, text) to service_role;
